///////////////////////////////////////////////////////////
//  SYS_ERFUELLT_AFO.cs
//  Implementation of the Enumeration SYS_ERFUELLT_AFO
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:38
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_ERFUELLT_AFO : int {

		True,
		False,
        NULL
        //{"true", "false"}
	}//end SYS_ERFUELLT_AFO

}//end namespace Systemelement