///////////////////////////////////////////////////////////
//  SYS_DETAILSTUFE.cs
//  Implementation of the Enumeration SYS_DETAILSTUFE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:38
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
    public enum SYS_DETAILSTUFE : int {

        unbestimmt,
        Uebergreifend,
		Null,
		Eins,
		Zwei,
		Drei,
		Vier,
		Fünf,
        NULL
        //{"unbestimmt", "Uebergreifend", "0", "1", "2", "3", "4", "5" };
	}//end SYS_DETAILSTUFE

}//end namespace Systemelement