///////////////////////////////////////////////////////////
//  SYS_SUBORDINATES_AFO.cs
//  Implementation of the Enumeration SYS_SUBORDINATES_AFO
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:40
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_SUBORDINATES_AFO : int {

		Sys_subordinates_Afo_true,
		Sys_subordinates_Afo_false,
        NULL
        //{"Sys_subordinates_Afo_true", "Sys_subordinates_Afo_false"}
    }//end SYS_SUBORDINATES_AFO

}//end namespace Systemelement