///////////////////////////////////////////////////////////
//  SYS_KOMPONENTENTYP.cs
//  Implementation of the Enumeration SYS_KOMPONENTENTYP
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:39
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_KOMPONENTENTYP : int {

		unbestimmt,
		System,
		Unterstützungssystem,
		Segment,
		HWEinheit,
		SWEinheit,
		ExterneEinheit,
		HWKomponente,
		SWKomponente,
		HWModul,
		ExternesHWModul,
		SWModul,
		ExternesSWModul,
		Datenspeicher,
		Verteilerelement,
		Service,
		ServiceLevel,
		PhysicalArchitecture,
		Entwurfsentscheidung,
		Schnittstelle,
        NULL
            /*
             {

    		"unbestimmt",
		"System",
		"Unterstützungssystem",
		"Segment",
		"HW-Einheit",
		"SW-Einheit",
		"Externe Einheit",
		"HW-Komponente",
		"SW-Komponente",
		"HW-Modul",
		"Externes HW-Modul",
		"SW-Modul",
		"Externes SW-Modul",
		"Datenspeicher",
		"Verteilerelement",
		"Service",
		"Service Level",
		"Physical Architecture",
		"Entwurfsentscheidung",
		"Schnittstelle"}
        */

	}//end SYS_KOMPONENTENTYP

}//end namespace Systemelement