///////////////////////////////////////////////////////////
//  SYS_ARTIKEL.cs
//  Implementation of the Enumeration SYS_ARTIKEL
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:37
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_ARTIKEL : int {

		der,
		die,
		das,
        NULL

	}//end SYS_ARTIKEL

}//end namespace Systemelement