///////////////////////////////////////////////////////////
//  SYS_TYP.cs
//  Implementation of the Enumeration SYS_TYP
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:41
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_TYP : int {

		Funktionsbaum,
		Szenarbaum,
		TechnischesSystem,
		C3Taxonomie,
		Qualitaetsmerkmal,
		Loesungen,
		Ausschreibungskriterium,
		Angebot,
        NULL
        //{"Funktionsbaum", "Szenarbaum", "Technisches System", "C3 Taxonomie", "Qualitaetsmerkmal", "Loesungen", "Ausschreibungskriterium", "Angebot"};
    }//end SYS_TYP

}//end namespace Systemelement