///////////////////////////////////////////////////////////
//  SYS_STATUS.cs
//  Implementation of the Enumeration SYS_STATUS
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:40
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_STATUS : int {

		geplant,
		realisiert,
		obsolet,
        NULL
        //{"geplant", "realisiert", "obsolet"};
    }//end SYS_STATUS

}//end namespace Systemelement