///////////////////////////////////////////////////////////
//  SYS_PRODUKT_STATUS.cs
//  Implementation of the Enumeration SYS_PRODUKT_STATUS
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 16:55:39
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum SYS_PRODUKT_STATUS : int {

		vomAGgesetzt,
		unbestimmt,
        NULL
        //{"vom AG gesetzt","unbestimmt"};
    }//end SYS_PRODUKT_STATUS

}//end namespace Systemelement