///////////////////////////////////////////////////////////
//  Element_Functional.cs
//  Implementation of the Class Element_Functional
//  Generated by Enterprise Architect
//  Created on:      23-Jan-2019 17:22:53
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Forms;
using System.Linq;
using System.Data.OleDb;
using Requirement_Plugin.Interfaces;

using System.Globalization;
using Database_Connection;
using Repsoitory_Elements;
using Requirements;

namespace Elements
{
    public class Element_Functional
    {

        public NodeType Client;
        public Activity Supplier;
        public List<Target_Functional> m_Target_Functional;
        public List<Requirement_Functional> m_Requirement_Functional;
       // public List<Requirement_Non_Functional> m_Requirement_Process;
        public List<Logical> m_Logical;
        public Capability Capability;
        public List<Element_Process> m_element_Processes;
        public List<Element_Measurement> m_element_measurement;


        public Element_Functional()
        {
            this.m_Target_Functional = new List<Target_Functional>();
            this.m_Requirement_Functional = new List<Requirement_Functional>();
          //  this.m_Requirement_Process = new List<Requirement_Non_Functional>();
            this.m_Logical = new List<Logical>();
            this.Capability = null;

            this.m_element_Processes = new List<Element_Process>();
            this.m_element_measurement = new List<Element_Measurement>();
        }

        ~Element_Functional()
        {

        }

        #region Check Elements
        /// <summary>
        /// Es wird überprüft, ob das Element_Functional ein Target mit dem Client und Supplier vorhanden ist.
        /// </summary>
        /// <param name="Client_GUID"></param>
        /// <param name="Supplier_GUID"></param>
        /// <returns></returns>
        public Target_Functional Check_Target(string Client_GUID, string Supplier_GUID)
        {
            if (this.m_Target_Functional.Count > 0)
            {
                int i1 = 0;
                do
                {
                    if (this.m_Target_Functional[i1].CLient_ID == Client_GUID && this.m_Target_Functional[i1].Supplier_ID == Supplier_GUID)
                    {
                        return (this.m_Target_Functional[i1]);
                    }

                    i1++;
                } while (i1 < this.m_Target_Functional.Count);
            }

            return (null);
        }

        public List<Target_Functional> Check_Target_ByClient(List<string> m_client)
        {
            List<Target_Functional> m_ret = new List<Target_Functional>();

            m_client = m_client.Distinct().ToList();

            if(m_client.Count > 0)
            {
                int i1 = 0;
                do
                {
                    List<Target_Functional> m_help = this.m_Target_Functional.Where(x => x.CLient_ID == m_client[i1]).ToList();

                    if(m_help.Count > 0)
                    {
                        m_ret.AddRange(m_help);
                    }

                    i1++;
                } while (i1 < m_client.Count);
            }

            return (m_ret);
        }
        public void Check_For_Requirement(EA.Repository repository, Requirement_Plugin.Database database)
        {
            if (this.Client != null && this.Supplier != null)
            {
              //  DB_Command command = new DB_Command();
             //   XML xML = new XML();
                TaggedValue taggedValue = new TaggedValue(database.metamodel, database);
                List<string> m_Type_req_func = database.metamodel.m_Requirement_Functional.Select(x => x.Type).ToList();
                List<string> m_Stereotype_req_func = database.metamodel.m_Requirement_Functional.Select(x => x.Stereotype).ToList();
                List<string> m_Type_DerivedElem = database.metamodel.m_Derived_Element.Select(x => x.Type).ToList();
                List<string> m_Stereotype_DerivedElem = database.metamodel.m_Derived_Element.Select(x => x.Stereotype).ToList();
                ////////////////////////////////////////////////////
                ///
               
                #region NodeType
                List<string> NodeType_Requ = new List<string>();
                Interface_Connectors_Requirement interface_Connectors = new Interface_Connectors_Requirement();
                List<string> help_guid = new List<string>();
                help_guid.Add(this.Client.Classifier_ID);
                NodeType_Requ = interface_Connectors.Get_Client_Element_By_Connector(database, help_guid, m_Type_req_func, m_Stereotype_req_func, m_Type_DerivedElem, m_Stereotype_DerivedElem, database.metamodel.m_Derived_Element[0].direction);
           
                #endregion NodeType
                #region Activity
                List<string> Activity_Requ = new List<string>();
                List<string> help_guid2 = new List<string>();
                help_guid2.Add(this.Supplier.Classifier_ID);
                Activity_Requ = interface_Connectors.Get_Client_Element_By_Connector(database, help_guid2, m_Type_req_func, m_Stereotype_req_func, m_Type_DerivedElem, m_Stereotype_DerivedElem, database.metamodel.m_Derived_Element[0].direction);

                /*var SQL_Activity2 = "SELECT ea_guid FROM t_object WHERE Object_Type IN(" + command.Add_Parameters_Pre(m_Type_req_func.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype_req_func.ToArray()) + ") AND Object_ID IN(SELECT Start_Object_ID FROM t_connector WHERE Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype_DerivedElem.ToArray()) + ") AND Connector_Type IN(" + command.Add_Parameters_Pre(m_Type_DerivedElem.ToArray()) + ") AND End_Object_ID IN (SELECT Object_ID FROM t_object WHERE ea_guid = ?));";

                OleDbCommand SELECT_Activity = new OleDbCommand(SQL_Activity2, (OleDbConnection)database.oLEDB_Interface.dbConnection);

                List<DB_Input[]> ee2 = new List<DB_Input[]>();
                List<string> help_guid2 = new List<string>();
                help_guid2.Add(this.Supplier.Classifier_ID);
                ee2.Add(help_guid2.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Stereotype_DerivedElem.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Type_DerivedElem.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Type_req_func.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Stereotype_req_func.Select(x => new DB_Input(-1, x)).ToArray());
                OleDbType[] m_input_Type2 = { OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar };
                database.oLEDB_Interface.Add_Parameters_Select(SELECT_Activity, ee2, m_input_Type2);
                string[] m_output2 = { "ea_guid" };

                List<DB_Return> m_ret4 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT_Activity, m_output2);

                if (m_ret4[0].Ret.Count > 1)
                {
                    Activity_Requ = m_ret4[0].Ret.GetRange(1, m_ret4[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList();
                }
                else
                {
                    Activity_Requ = null;
                }
                */
                #endregion Activity
                if (NodeType_Requ != null && Activity_Requ != null)
                {
                    int i1 = 0;
                    do
                    {
                        if (Activity_Requ.Contains(NodeType_Requ[i1]))
                        {
                            Requirement_Functional requirement_Functional = new Requirement_Functional(" ", " ", " ", " ", " ", " ", true, " ", true, NodeType_Requ[i1], database.metamodel);
                            requirement_Functional.Classifier_ID = NodeType_Requ[i1];
                            requirement_Functional.Get_Tagged_Values_From_Requirement(NodeType_Requ[i1], repository, database);
                            

                            if (this.m_Requirement_Functional.Contains(requirement_Functional) == false)
                            {
                                this.m_Requirement_Functional.Add(requirement_Functional);

                                //Zuordnung Element_Functional zu einer Capability
                                Check_For_Capability(repository, database);
                                //Check Issue
                                requirement_Functional.Get_Issues(database);
                                //Check Klärungspunkte
                                requirement_Functional.Check_Klärungspunkte(requirement_Functional.m_Issues, database, repository);

                                  
                            }
                        }

                        i1++;
                    } while (i1 < NodeType_Requ.Count);
                }
                //////////////////////////////////////////////////////////
                //Nun alle Targets
                if (this.m_Target_Functional.Count > 0)
                {
                    int i2 = 0;
                    do
                    {
                        this.m_Target_Functional[i2].Check_For_Requirement(repository, database, this);

                        i2++;
                    } while (i2 < this.m_Target_Functional.Count);
                }
            }
        }//end Element_Functional

        public void Check_For_Capability(EA.Repository repository, Requirement_Plugin.Database database)
        {
            Capability capability = null;
            DB_Command command = new DB_Command();
           // XML xML = new XML();
            List<string> m_Type_DerivedCap = database.metamodel.m_Derived_Capability.Select(x => x.Type).ToList();
            List<string> m_Stereotype_DerivedCap = database.metamodel.m_Derived_Capability.Select(x => x.Stereotype).ToList();
            List<string> m_Capability_Type = database.metamodel.m_Capability.Select(x => x.Type).ToList();
            List<string> m_Capability_Stereotype = database.metamodel.m_Capability.Select(x => x.Stereotype).ToList();

            if (this.m_Requirement_Functional.Count > 0)
            {
                /*var SQL = "SELECT ea_guid FROM t_object WHERE Object_Type IN"+xML.SQL_IN_Array(m_Capability_Type.ToArray())+" AND Stereotype IN"+xML.SQL_IN_Array(m_Capability_Stereotype.ToArray())+" AND Object_ID IN( SELECT End_Object_ID FROM t_connector WHERE Stereotype IN" + xML.SQL_IN_Array(m_Stereotype_DerivedCap.ToArray()) + " AND Connector_Type IN" + xML.SQL_IN_Array(m_Type_DerivedCap.ToArray()) + " AND Start_Object_ID IN (SELECT Object_ID FROM t_object WHERE ea_guid = '" + this.m_Requirement_Functional[0].Classifier_ID + "'));";

               // string Name = this.m_Requirement_Functional[0].Get_Name_t_object_GUID(repository, database);

                string xml_String = repository.SQLQuery(SQL);
                List<string> GUID = xML.Xml_Read_Attribut("ea_guid", xml_String);
                */

                List<string> GUID = new List<string>();
                List<string> help_guid2 = new List<string>();
                help_guid2.Add(this.m_Requirement_Functional[0].Classifier_ID);
                Interface_Connectors interface_Connectors = new Interface_Connectors();
                GUID = interface_Connectors.Get_Supplier_Element_By_Connector(database, help_guid2, m_Capability_Type, m_Capability_Stereotype, m_Type_DerivedCap, m_Stereotype_DerivedCap);
              /*  var SQL2 = "SELECT ea_guid FROM t_object WHERE Object_Type IN(" + command.Add_Parameters_Pre(m_Capability_Type.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Capability_Stereotype.ToArray()) + ") AND Object_ID IN( SELECT End_Object_ID FROM t_connector WHERE Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype_DerivedCap.ToArray()) + ") AND Connector_Type IN(" + command.Add_Parameters_Pre(m_Type_DerivedCap.ToArray()) + ") AND Start_Object_ID IN (SELECT Object_ID FROM t_object WHERE ea_guid = ?));";

                OleDbCommand SELECT_Capbility = new OleDbCommand(SQL2, (OleDbConnection)database.oLEDB_Interface.dbConnection);

                List<DB_Input[]> ee2 = new List<DB_Input[]>();
                List<string> help_guid2 = new List<string>();
                help_guid2.Add(this.m_Requirement_Functional[0].Classifier_ID);
                ee2.Add(help_guid2.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Stereotype_DerivedCap.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Type_DerivedCap.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Capability_Type.Select(x => new DB_Input(-1, x)).ToArray());
                ee2.Add(m_Capability_Stereotype.Select(x => new DB_Input(-1, x)).ToArray());
                OleDbType[] m_input_Type2 = { OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar };
                database.oLEDB_Interface.Add_Parameters_Select(SELECT_Capbility, ee2, m_input_Type2);
                string[] m_output2 = { "ea_guid" };

                List<DB_Return> m_ret4 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT_Capbility, m_output2);

                if (m_ret4[0].Ret.Count > 1)
                {
                    GUID = m_ret4[0].Ret.GetRange(1, m_ret4[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList();
                }
                else
                {
                    GUID = null;
                }
                */

                if (GUID != null)
                {
                    Capability cap = database.Check_Capability_Database(GUID[0]);

                    if (cap != null)
                    {

                        this.Capability = cap;
                        if (this.m_Requirement_Functional[0].m_Capability.Contains(cap) == false)
                        {
                            this.m_Requirement_Functional[0].m_Capability.Add(cap);
                        }

                    }
                }


            }
        }
        #endregion Check Elements

        #region Create Elements

        public bool Create_Target_Functional(string Client_GUID, string Supplier_GUID, EA.Repository repository, Requirement_Plugin.Database database)
        {
            if (Client_GUID != null && Supplier_GUID != null)
            {
                Target_Functional recent = new Target_Functional();
                recent.CLient_ID = Client_GUID;
                recent.Supplier_ID = Supplier_GUID;

                if(Supplier.m_GUID.Contains(Supplier_GUID) == false)
                {
                    Supplier.m_GUID.Add(Supplier_GUID);
                }

                Repository_Element rep = new Repository_Element();

                //MessageBox.Show(rep.Get_Name_t_object_GUID(repository));

                //Logical erhalten 
                Logical logical = recent.Get_Logical(Client_GUID, Supplier_GUID, repository, database);
                //        var theElement = repository.GetElementByGuid(Supplier_GUID);
                //        var theElement2 = repository.GetElementByGuid(Client_GUID);
                //                MessageBox.Show(theElement2.Name + " --> " + theElement.Name);

                if (logical != null && this.m_Logical.Contains(logical) == false)
                {
                    this.m_Logical.Add(logical);
                }

                this.m_Target_Functional.Add(recent);

                return (true);
            }

            return (false);
        }
        #endregion Create Elements

        #region Get
        public List<string> Get_Client_GUID_Target()
        {
            List<string> m_GUID = new List<string>();

            int i1 = 0;
            do
            {
                if(m_GUID.Contains(this.m_Target_Functional[i1].CLient_ID) == false)
                {
                    m_GUID.Add(this.m_Target_Functional[i1].CLient_ID);
                }

                i1++;
            } while (i1 < this.m_Target_Functional.Count);

            if (m_GUID.Contains(this.Client.Classifier_ID) == false)
            {
                m_GUID.Add(this.Client.Classifier_ID);
            }

            return (m_GUID);

        }



        public List<string> Get_Client_GUID_Target_By_SupplierID(string Supplier_ID)
        {
            List<string> m_ret = new List<string>();

            if(this.m_Target_Functional.Count > 0)
            {
                int i1 = 0;
                do
                {

                    if (this.m_Target_Functional[i1].Supplier_ID == Supplier_ID)
                    {
                        if (m_ret.Contains(this.m_Target_Functional[i1].CLient_ID) == false)
                        {
                            m_ret.Add(this.m_Target_Functional[i1].CLient_ID);
                        }
                    }
                    i1++;
                } while (i1 < this.m_Target_Functional.Count);
            }

          


            return (m_ret);
        }


        public List<string> Get_Supplier_GUID_Target()
        {
            List<string> m_GUID = new List<string>();

            int i1 = 0;
            do
            {
                if (m_GUID.Contains(this.m_Target_Functional[i1].Supplier_ID) == false)
                {
                    m_GUID.Add(this.m_Target_Functional[i1].Supplier_ID);
                }

                i1++;
            } while (i1 < this.m_Target_Functional.Count);

            if (m_GUID.Contains(this.Supplier.Classifier_ID) == false)
            {
                m_GUID.Add(this.Supplier.Classifier_ID);
            }

            return (m_GUID);
        }


        public List<Element_Process> Transform_Node_Element_Proces(List<string> m_Node_ID2, SysElement sys)
        {
            List<Element_Process> m_ret = new List<Element_Process>();

            //List<Element_Process> m_save = this.m_element_Processes;

            if (this.m_element_Processes.Count > 0)
            {
                int i1 = 0;
                do
                {
                    List<string> m_help2 = m_element_Processes[i1].m_Node_ID.Intersect(m_Node_ID2).ToList();

                    //Noch nicht vorhanden
                    if(m_ret.Select(x => x.OpConstraint.Classifier_ID).Contains(m_element_Processes[i1].OpConstraint.Classifier_ID) == false)
                    {
                        if (m_help2.Count > 0)
                        {
                            Element_Process element_Process = new Element_Process(m_element_Processes[i1].activity, m_element_Processes[i1].OpConstraint, m_element_Processes[i1].flag_Activity);
                            element_Process.capability = m_element_Processes[i1].capability;
                            element_Process.m_Action_ID = m_element_Processes[i1].m_Action_ID.Intersect(this.m_Target_Functional.Select(x => x.Supplier_ID).ToList()).ToList();
                            element_Process.m_GUID_Client = m_element_Processes[i1].m_GUID_Client.Intersect(this.m_Target_Functional.Select(x => x.CLient_ID).ToList()).ToList();
                            element_Process.m_Node_ID = m_help2;
                            element_Process.Requirement_Process = m_element_Processes[i1].Requirement_Process;

                            m_ret.Add(element_Process);
                        }
                    }
                    else//Vorhanden
                    {
                        List<Element_Process> m_process = m_ret.Where(x => x.OpConstraint.Classifier_ID == m_element_Processes[i1].OpConstraint.Classifier_ID).ToList();
                 
                        if(m_process.Count > 0)
                        {
                            m_process[0].m_Action_ID.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_Action_ID.Distinct();
                            m_process[0].m_GUID_Client.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_GUID_Client.Distinct();
                            m_process[0].m_Node_ID.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_Node_ID.Distinct();
                        }
                    
                    }
                    i1++;
                } while (i1 < this.m_element_Processes.Count);
            }



            return (m_ret);
        }

        public List<Element_Measurement> Transform_Node_Element_Measurement(List<string> m_Node_ID2, SysElement sys, Requirement_Plugin.Database database)
        {
            List<Element_Measurement> m_ret = new List<Element_Measurement>();

            //List<Element_Process> m_save = this.m_element_Processes;

            if (this.m_element_measurement.Count > 0)
            {
                int i1 = 0;
                do
                {
                    List<Element_Functional> m_help = sys.m_Element_Functional.Where(x => x.Supplier == this.Supplier).ToList();

                    if(m_help[0].m_element_measurement.Select(y => y.Measurement.Classifier_ID).Contains(this.m_element_measurement[i1].Measurement.Classifier_ID) == false)
                    {
                        Element_Measurement element_Measurement = new Element_Measurement(this.m_element_measurement[i1].Measurement, database);
                        element_Measurement.m_guid_Instanzen = this.m_element_measurement[i1].m_guid_Instanzen;
                        element_Measurement.m_requirement = this.m_element_measurement[i1].m_requirement;

                        m_help[0].m_element_measurement.Add(element_Measurement);

                    }
                    
               /*     List<string> m_help2 = m_element_Processes[i1].m_Node_ID.Intersect(m_Node_ID2).ToList();

                    //Noch nicht vorhanden
                    if (m_ret.Select(x => x.OpConstraint.Classifier_ID).Contains(m_element_Processes[i1].OpConstraint.Classifier_ID) == false)
                    {
                        if (m_help2.Count > 0)
                        {
                            Element_Process element_Process = new Element_Process(m_element_Processes[i1].activity, m_element_Processes[i1].OpConstraint, m_element_Processes[i1].flag_Activity);
                            element_Process.capability = m_element_Processes[i1].capability;
                            element_Process.m_Action_ID = m_element_Processes[i1].m_Action_ID.Intersect(this.m_Target_Functional.Select(x => x.Supplier_ID).ToList()).ToList();
                            element_Process.m_GUID_Client = m_element_Processes[i1].m_GUID_Client.Intersect(this.m_Target_Functional.Select(x => x.CLient_ID).ToList()).ToList();
                            element_Process.m_Node_ID = m_help2;
                            element_Process.Requirement_Process = m_element_Processes[i1].Requirement_Process;

                            m_ret.Add(element_Process);
                        }
                    }
                    else//Vorhanden
                    {
                        List<Element_Process> m_process = m_ret.Where(x => x.OpConstraint.Classifier_ID == m_element_Processes[i1].OpConstraint.Classifier_ID).ToList();

                        if (m_process.Count > 0)
                        {
                            m_process[0].m_Action_ID.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_Action_ID.Distinct();
                            m_process[0].m_GUID_Client.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_GUID_Client.Distinct();
                            m_process[0].m_Node_ID.AddRange(m_element_Processes[i1].m_Action_ID);
                            m_process[0].m_Node_ID.Distinct();
                        }

                    }
               */
                    i1++;
                } while (i1 < this.m_element_measurement.Count);
            }

            m_ret = sys.m_Element_Functional.Where(y => y.Supplier == this.Supplier).SelectMany(x => x.m_element_measurement).ToList();

            return (m_ret);
        }
        #endregion

        #region Copy
        public Element_Functional Copy_element_Functional(NodeType Target, EA.Repository repository, Requirement_Plugin.Database database)
        {
            Element_Functional element_Functional = new Element_Functional();
            element_Functional.Supplier = this.Supplier;

            element_Functional.Supplier.m_Element_Functional.Add(element_Functional);

            element_Functional.Client = Target;
            // element_Functional.m_Target_Functional = this.m_Target_Functional;
            //Targets
            if(this.m_Target_Functional.Count > 0)
            {
                int i1 = 0;
                do
                {
                    Target_Functional target = new Target_Functional();
                    target.CLient_ID = Target.Classifier_ID;
                    target.Supplier_ID = this.m_Target_Functional[i1].Supplier_ID;

                    element_Functional.m_Target_Functional.Add(target);

                    i1++;
                } while (i1 < this.m_Target_Functional.Count);
            }
           //Prozesse
           if(this.m_element_Processes.Count > 0)
            {
                int i1 = 0;
                do
                {
                    Element_Process element_Process = new Element_Process(this.m_element_Processes[i1].activity, this.m_element_Processes[i1].OpConstraint, this.m_element_Processes[i1].flag_Activity);
                    element_Process.m_Action_ID = this.m_element_Processes[i1].m_Action_ID;
                    element_Process.m_Node_ID.Add(Target.Classifier_ID);

                    element_Process.Check_Requirement_Process(database, repository);

                    element_Functional.m_element_Processes.Add(element_Process);


                    i1++;
                } while (i1 < this.m_element_Processes.Count);
            }
           //Measurements
           if(this.m_element_measurement.Count > 0)
            {
                int i1 = 0;
                do
                {
                    Element_Measurement element_Measurement = new Element_Measurement(this.m_element_measurement[i1].Measurement, database);
                    element_Measurement.m_guid_Instanzen.Add(Target.Classifier_ID);

                    element_Measurement.Check_For_Requirement(1, repository, database, this.Supplier, this.Client);

                    element_Functional.m_element_measurement.Add(element_Measurement);

                   i1++;
                } while (i1 < this.m_element_measurement.Count);

             
            }


            element_Functional.Capability = this.Capability;
           
            element_Functional.m_Logical = this.m_Logical;

            //Anforderung überprüfen
            element_Functional.Check_For_Requirement(repository, database);

            return (element_Functional);
        }
        #endregion

        #region Requirmenet
        /// <summary>
        /// Automatisierte Erstellung von Default Anforderungen.
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="database"></param>
        public void Create_Requirement_Functional(EA.Repository repository, Requirement_Plugin.Database database, string Package_GUID)
        {
            TextInfo ti = CultureInfo.CurrentCulture.TextInfo;

            if (this.m_Requirement_Functional.Count == 0)
            {
                #region AFO_Parameter
                //W_Object
                string W_Object = this.Supplier.W_Object;
                //W_Prozesswort
                string W_Prozesswort = this.Supplier.W_Prozesswort;
                //W_Qualitaet
                string W_Qualitaet = "";
                //W_Randbedingung
                string W_Randbedingung = "";
                //W_Singular
                bool W_Singular = this.Client.W_SINGULAR;
                //W_Subject
                string W_Subject = this.Client.W_Artikel+" "+this.Client.Name;
                //W_Zu
                bool W_zu = false;
                //recent_guid
                string recent_guid = "";
                //Titel
                string Titel = this.Client.Name + " - " + W_Prozesswort + " " + W_Object;
                //Text
                string AFO_Text = "";

                if(W_Singular == true)
                {
                    AFO_Text = ti.ToTitleCase(this.Client.W_Artikel) + " " + Client.Name +" "+ database.metamodel.m_Verbindlichkeit[0] + " " + W_Object + " " + W_Prozesswort + ".";
                }
                else
                {
                    AFO_Text = ti.ToTitleCase(this.Client.W_Artikel) + " " + Client.Name + " "+ database.metamodel.m_Verbindlichkeit[1] + " "+  W_Object + " " + W_Prozesswort + ".";
                }
                #endregion

                #region AFO Erzeugung
                Requirement_Functional requirement_Functional = new Requirement_Functional(Titel, AFO_Text, W_Object, W_Prozesswort, W_Qualitaet, W_Randbedingung, W_Singular, W_Subject, W_zu, recent_guid, database.metamodel);
                requirement_Functional.Classifier_ID =  requirement_Functional.Create_Requirement_funktional(repository, Package_GUID, database.metamodel.m_Requirement_Functional.Select(x => x.Stereotype).ToList()[0], database);
                this.m_Requirement_Functional.Add(requirement_Functional);
                #endregion AFO Erzeugung
                #region Konnektoren anlegen

                #region NodeType
                //NodeType
                Create_Connectoren_NodeType(database, repository);
                #endregion
                //Activity
                #region Activity 
                Create_Connectoren_Activity(database, repository);
                #endregion
                //Parent Anforderung
                #region Parent AFO
                Create_Connectoren_Parent(database, repository);
                #endregion
                //Child Anforderung
                #region Child Anforderung
                Create_Connectoren_Child(database, repository);
                #endregion
                //Duplicate mit Element User, welche selbe Activität und NodeType haben
                #region Duplicate
                Create_Connectoren_Duplicate(database, repository);
                #endregion
                //Duplicate Generalsiserung
                Create_Connectoren_Duplicate_Generalisierung(database, repository);

                #region Requirement Process hinzufügen
                Create_Connectoren_Process(database, repository);
                #endregion
                #endregion
            }
        }

        public void Update_Connectoren_Requirement_Functional(EA.Repository repository, Requirement_Plugin.Database database)
        {
            Create_Connectoren_NodeType(database, repository);
            Create_Connectoren_Activity(database, repository);
            Create_Connectoren_Parent(database, repository);
            Create_Connectoren_Child(database, repository);
            Create_Connectoren_Duplicate(database, repository);
            Create_Connectoren_Duplicate_Generalisierung(database, repository);
            Create_Connectoren_Process(database, repository);
            Create_Refines_Measurement(database, repository);

        }
        #endregion

        public void Create_Requirement_Quality(EA.Repository repository, Requirement_Plugin.Database database, string Package_GUID)
        {
            if(this.m_element_measurement.Count > 0)
            {
                int i1 = 0;
                do
                {
                    this.m_element_measurement[i1].Create_Requirement_Activity(repository, database, this.Client, this.Supplier, Package_GUID);

                    i1++;
                } while (i1 < this.m_element_measurement.Count);
            }
        }

        public void Update_Connectoren_QualityAcitvity(EA.Repository repository, Requirement_Plugin.Database database)
        {
            if(this.m_element_measurement.Count > 0)
            {
                int i1 = 0;
                do
                {
                    this.m_element_measurement[i1].Update_Connectoren_QualityActivity(repository, database, this.Client, this.Supplier);

                    i1++;
                } while (i1 < this.m_element_measurement.Count);
            }
        }

        #region Connetoren Requirement
        private void Create_Connectoren_NodeType(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();
            List<string> m_NodeID = this.Get_Client_GUID_Target();
            if (m_NodeID.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_NodeID[i1], database.metamodel.m_Derived_Element.Select(x => x.Stereotype).ToList(), database.metamodel.m_Derived_Element.Select(x => x.Type).ToList(), database.metamodel.m_Derived_Element[0].SubType, repository, database, database.metamodel.m_Derived_Element[0].Toolbox, database.metamodel.m_Derived_Element[0].direction);
                    i1++;
                } while (i1 < m_NodeID.Count);
            }
        }
        private void Create_Connectoren_Activity(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();
            List<string> m_ActionID = this.Get_Supplier_GUID_Target();
            if (m_ActionID.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_ActionID[i1], database.metamodel.m_Derived_Element.Select(x => x.Stereotype).ToList(), database.metamodel.m_Derived_Element.Select(x => x.Type).ToList(), database.metamodel.m_Derived_Element[0].SubType, repository, database, database.metamodel.m_Derived_Element[0].Toolbox, database.metamodel.m_Derived_Element[0].direction);
                    i1++;
                } while (i1 < m_ActionID.Count);
            }
        }
        private void Create_Connectoren_Parent(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();
            List<Element_Functional> m_parent_func = this.Supplier.m_Parent.SelectMany(x => x.m_Element_Functional).ToList();
            List<Requirement_Functional> m_req_func = m_parent_func.SelectMany(x => x.m_Requirement_Functional).ToList();
            if (m_req_func.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_req_func[i1].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines[0].SubType, repository, database, database.metamodel.m_Afo_Refines[0].Toolbox, database.metamodel.m_Afo_Refines[0].direction);

                    i1++;
                } while (i1 < m_req_func.Count);
            }
            //User
            List<Element_User> m_parent_user = this.Supplier.m_Parent.SelectMany(x => x.m_Element_User).ToList();
            List<Requirement_User> m_req_user = m_parent_user.SelectMany(x => x.m_Requirement_User).ToList();
            if (m_req_user.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_req_user[i1].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines[0].SubType, repository, database, database.metamodel.m_Afo_Refines[0].Toolbox, database.metamodel.m_Afo_Refines[0].direction);

                    i1++;
                } while (i1 < m_req_user.Count);
            }
        }
        private void Create_Connectoren_Child(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();
            List<Element_Functional> m_child_func = this.Supplier.m_Child.SelectMany(x => x.m_Element_Functional).ToList();
            List<Requirement_Functional> m_req_child_func = m_child_func.SelectMany(x => x.m_Requirement_Functional).ToList();
            if (m_req_child_func.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(m_req_child_func[i1].Classifier_ID, this.m_Requirement_Functional[0].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines[0].SubType, repository, database, database.metamodel.m_Afo_Refines[0].Toolbox, database.metamodel.m_Afo_Refines[0].direction);

                    i1++;
                } while (i1 < m_req_child_func.Count);
            }
            //User
            List<Element_User> m_child_user = this.Supplier.m_Child.SelectMany(x => x.m_Element_User).ToList();
            List<Requirement_User> m_req_child_user = m_child_user.SelectMany(x => x.m_Requirement_User).ToList();
            if (m_req_child_user.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(m_req_child_user[i1].Classifier_ID, this.m_Requirement_Functional[0].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines[0].SubType, repository, database, database.metamodel.m_Afo_Refines[0].Toolbox, database.metamodel.m_Afo_Refines[0].direction);

                    i1++;
                } while (i1 < m_req_child_user.Count);
            }
        }
        private void Create_Connectoren_Duplicate(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();
            List<Element_User> m_duplicate = this.Supplier.m_Element_User.Where(x => x.Client == this.Client).ToList();
            List<Requirement_Functional> m_req_duplicate_ = m_duplicate.SelectMany(x => x.m_Requirement_Functional).ToList();
            if (m_req_duplicate_.Count > 0)
            {
                int i1 = 0;
                do
                {
                    repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_req_duplicate_[i1].Classifier_ID, database.metamodel.m_Afo_Dublette.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Dublette.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Dublette[0].SubType, repository, database, database.metamodel.m_Afo_Dublette[0].Toolbox, database.metamodel.m_Afo_Dublette[0].direction);

                    i1++;
                } while (i1 < m_req_duplicate_.Count);
            }
        }

        private void Create_Connectoren_Duplicate_Generalisierung(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();

            #region Generalsiierung runter
            List<NodeType> m_Specilize = new List<NodeType>();
            m_Specilize = this.Client.m_Specialize;

            if(m_Specilize.Count > 0)
            {
                
                    List<Element_Functional> m_duplicate = m_Specilize.SelectMany(x => x.m_Element_Functional.Where(y => y.Supplier == this.Supplier)).ToList();
                    List<Requirement_Functional> m_req_duplicate_ = m_duplicate.SelectMany(x => x.m_Requirement_Functional).ToList();

                    if (m_req_duplicate_.Count > 0)
                    {
                        int i1 = 0;
                        do
                        {
                            repository_Connector.Create_Dependency(m_req_duplicate_[i1].Classifier_ID,this.m_Requirement_Functional[0].Classifier_ID, database.metamodel.m_Afo_Dublette.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Dublette.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Dublette[0].SubType, repository, database, database.metamodel.m_Afo_Dublette[0].Toolbox, database.metamodel.m_Afo_Dublette[0].direction);

                            i1++;
                        } while (i1 < m_req_duplicate_.Count);
                    }
                    List<Element_User> m_duplicate2 = m_Specilize.SelectMany(x => x.m_Element_User.Where(y => y.Supplier == this.Supplier)).ToList();
                    List<Requirement_User> m_req_duplicate2_ = m_duplicate2.SelectMany(x => x.m_Requirement_User).ToList();

                    if (m_req_duplicate2_.Count > 0)
                    {
                        int i1 = 0;
                        do
                        {
                            repository_Connector.Create_Dependency(m_req_duplicate2_[i1].Classifier_ID, this.m_Requirement_Functional[0].Classifier_ID,  database.metamodel.m_Afo_Dublette.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Dublette.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Dublette[0].SubType, repository, database, database.metamodel.m_Afo_Dublette[0].Toolbox, database.metamodel.m_Afo_Dublette[0].direction);

                            i1++;
                        } while (i1 < m_req_duplicate2_.Count);
                    }
                
            }
            #endregion

            #region Generalisierung hoch
            List<NodeType> m_Specified = this.Client.Get_All_SpecifiedBy(database.m_NodeType);

            if (m_Specified != null)
            {

                List<Element_Functional> m_duplicate = m_Specified.SelectMany(x => x.m_Element_Functional.Where(y => y.Supplier == this.Supplier)).ToList();
                List<Requirement_Functional> m_req_duplicate_ = m_duplicate.SelectMany(x => x.m_Requirement_Functional).ToList();

                if (m_req_duplicate_.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_req_duplicate_[i1].Classifier_ID,  database.metamodel.m_Afo_Dublette.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Dublette.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Dublette[0].SubType, repository, database, database.metamodel.m_Afo_Dublette[0].Toolbox, database.metamodel.m_Afo_Dublette[0].direction);

                        i1++;
                    } while (i1 < m_req_duplicate_.Count);
                }
                List<Element_User> m_duplicate2 = m_Specified.SelectMany(x => x.m_Element_User.Where(y => y.Supplier == this.Supplier)).ToList();
                List<Requirement_User> m_req_duplicate2_ = m_duplicate2.SelectMany(x => x.m_Requirement_User).ToList();

                if (m_req_duplicate2_.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        repository_Connector.Create_Dependency(this.m_Requirement_Functional[0].Classifier_ID, m_req_duplicate2_[i1].Classifier_ID,  database.metamodel.m_Afo_Dublette.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Dublette.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Dublette[0].SubType, repository, database, database.metamodel.m_Afo_Dublette[0].Toolbox, database.metamodel.m_Afo_Dublette[0].direction);

                        i1++;
                    } while (i1 < m_req_duplicate2_.Count);
                }

            }
            #endregion
           
        }

        private void Create_Connectoren_Process(Requirement_Plugin.Database database, EA.Repository repository)
        {
            Repository_Connector repository_Connector = new Repository_Connector();

            List<Requirement_Non_Functional> m_req_process = this.Supplier.Element_Process_Get_NodeType_Requirement(this.Client);

            if(m_req_process.Count > 0)
            {
                int i1 = 0;
                do
                {
                    if(m_req_process[i1] != null)
                    {
                        repository_Connector.Create_Dependency(m_req_process[i1].Classifier_ID, this.m_Requirement_Functional[0].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines[0].SubType, repository, database, database.metamodel.m_Afo_Refines[0].Toolbox, database.metamodel.m_Afo_Refines[0].direction);


                    }

                    i1++;
                } while (i1 < m_req_process.Count);
            }


        }
        
        public void Create_Refines_Measurement(Requirement_Plugin.Database database, EA.Repository repository)
        {
            if(this.m_element_measurement.Count > 0)
            {
                Repository_Connector repository_Connectors = new Repository_Connector();

                int i1 = 0;
                do
                {
                    if(this.m_element_measurement[i1].m_requirement.Count > 0 && this.m_Requirement_Functional[0] != null)
                    {
                        int i2 = 0;
                        do
                        {
                            if (this.m_element_measurement[i1].m_requirement[i2].Classifier_ID != null && this.m_Requirement_Functional[0].Classifier_ID != null)
                            {
                                repository_Connectors.Create_Dependency(this.m_element_measurement[i1].m_requirement[i2].Classifier_ID, this.m_Requirement_Functional[0].Classifier_ID, database.metamodel.m_Afo_Refines.Select(x => x.Stereotype).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.Type).ToList(), database.metamodel.m_Afo_Refines.Select(x => x.SubType).ToList()[0], repository, database, database.metamodel.m_Afo_Refines.Select(x => x.Toolbox).ToList()[0], database.metamodel.m_Afo_Refines[0].direction);
                            }

                            i2++;
                        } while (i2 < this.m_element_measurement[i1].m_requirement.Count);

                              
                    }

                    i1++;
                } while (i1 < this.m_element_measurement.Count);
            }
        }

        #endregion
    }
}//end namespace Requirement_Plugin