///////////////////////////////////////////////////////////
//  Repository_Element.cs
//  Implementation of the Class Repository_Element
//  Generated by Enterprise Architect
//  Created on:      14-Jan-2019 17:01:34
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.OleDb;
using System.Xml;
using System.Linq;
using Requirement_Plugin.Interfaces;
using System.Windows.Forms;

using Database_Connection;
using Metamodels;
using Requirement_Plugin;

//using Requirement_Plugin;
namespace Repsoitory_Elements
{
	public class Repository_Element : Repository_Plugin
    {

        
		public string Classifier_ID;
        public int ID;
		public string Name { get; set; }
        public string Author { get; set; }
        public string Notes { get; set; }
        public Repository_Elements m_Repository_Elements;
        public List<Issue> m_Issues;
        //public List<Requirement_Plugin.Repository_Elements.Measurement> m_Measurement;

		public Repository_Element(){
            this.m_Issues = new List<Issue>();
          //  this.m_Measurement = new List<Requirement_Plugin.Repository_Elements.Measurement>();
		}

		~Repository_Element(){

		}
        #region Update Attribute

        public void Update_Name(EA.Repository repository, string name)
        {
            if (this.Classifier_ID != null)
            {
               // element = new EA.Element();
                EA.Element element = repository.GetElementByGuid(this.Classifier_ID);
                if(element != null)
                {
                    element.Name = name;
                    element.Update();
                }
                
            }
        }

        public void Update_Notes(EA.Repository repository, string notes)
        {
            if (this.Classifier_ID != null)
            {
                //EA.Element element = new EA.Element();
                EA.Element element = repository.GetElementByGuid(this.Classifier_ID);
                if(element != null)
                {
                    element.Notes = notes;
                    element.Update();
                }
              
            }

        }
        #endregion

        #region Check_Element
        public string Check_Element_Name(string name, Database database, string Type, string Stereotype, int ParentID)
        {
            string ret = null;

            Interface_Element interface_Element = new Interface_Element();

            string ret_guid = interface_Element.Check_Database_Element_Class(database, Type, Stereotype, name, ParentID);

            if(ret_guid != null)
            {
                ret = ret_guid;
            }

            return (ret);
        }
        #endregion

        #region Get
        public void Get_Issues(Database database)
        {
            Interface_Connectors interface_Collection = new Interface_Connectors();
            Interface_Collection interface_Collection2 = new Interface_Collection();

            List<string> m_Type = database.metamodel.m_Issue.Select(x => x.Type).ToList();
            List<string> m_Stereotype = database.metamodel.m_Issue.Select(x => x.Stereotype).ToList();
            List<string> m_Type_con = database.metamodel.m_Con_Trace.Select(x => x.Type).ToList();
            List<string> m_Stereotype_con = database.metamodel.m_Con_Trace.Select(x => x.Stereotype).ToList();
            List<string> m_Supplier_Guid = new List<string>();
            m_Supplier_Guid.Add(this.Classifier_ID);

            List<string> m_GUID = interface_Collection.Get_Client_Element_By_Connector(database, m_Supplier_Guid, m_Type, m_Stereotype, m_Type_con, m_Stereotype_con);

          //  List<string> m_GUID2 = interface_Collection2.Get_Elements_GUID(database, m_Type, m_Stereotype);

            if(m_GUID != null)
            {
                int i1 = 0;

                do
                {
                    Repository_Element repository_Element = new Repository_Element();
                    repository_Element.Classifier_ID = m_GUID[i1];
                    this.Name = repository_Element.Get_Name(database);
                    this.Notes = repository_Element.Get_Notes(database);

                    Issue recent = new Issue(database, this.Name, this.Notes, null, null, false, null);

                    if(this.m_Issues.Contains(recent) == false)
                    {
                        this.m_Issues.Add(recent);
                    }

                    i1++;
                } while (i1 < m_GUID.Count);
            }
           
        }

        public List<Requirement_Plugin.Repository_Elements.Measurement> Get_Measurement(string guid, Database database)
        {
            List<Requirement_Plugin.Repository_Elements.Measurement> m_ret = new List<Requirement_Plugin.Repository_Elements.Measurement>();
            List<string> m_guid = null;

            if (guid == this.Classifier_ID)
            {
               m_guid = this.Get_Children_Guid(database, database.metamodel.m_Measurement_Usage.Select(x => x.Type).ToList(), database.metamodel.m_Measurement_Usage.Select(x => x.Stereotype).ToList());
            }
            else
            {
                m_guid = this.Get_Children_Guid_Instanzen(database, guid, database.metamodel.m_Measurement_Usage.Select(x => x.Type).ToList(), database.metamodel.m_Measurement_Usage.Select(x => x.Stereotype).ToList());
            }

           

            if (m_guid != null)
            {
                int i1 = 0;
                do
                {
                    Requirement_Plugin.Repository_Elements.Measurement recent_measure = new Requirement_Plugin.Repository_Elements.Measurement(m_guid[i1], database );

                    if(m_ret.Contains(recent_measure) == false)
                    {
                        m_ret.Add(recent_measure);
                    }


                    i1++;
                } while (i1 < m_guid.Count);
            }

            if(m_ret.Count == 0)
            {
                m_ret = null;
            }

            return (m_ret);
        }
      
        #endregion Get

        #region Attribute
        public string Get_Name(Database database)
        {


            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "Name"));
            }
            else
            {
                return (null);
            }
        }
        public string Get_Notes(Database database)
        {


            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "Note"));
            }
            else
            {
                return (null);
            }
        }
        public string Get_GUID(EA.Repository Repository, Database database)
        {


            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "ea_guid"));
            }
            else
            {
                return (null);
            }

        }
        public string Get_Author(Database database)
        {

            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "Author"));
            }
            else
            {
                return (null);
            }

        }
        public int Get_Object_ID(Database database)
        {

            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_Integer(this.Classifier_ID, database, "Object_ID", "t_object"));
            }
            else
            {
                return (-1);
            }
        }
        public int Get_Package_ID(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_Integer(this.Classifier_ID, database, "Package_ID", "t_object"));
            }
            else
            {
                return (-1);
            }
        }
        public string Get_Type(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "Object_Type"));
            }
            else
            {
                return (null);
            }
        }
        public string Get_Stereotype(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "Stereotype"));
            }
            else
            {
                return (null);
            }
        }
        public string Get_Classifier(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(this.Classifier_ID, database, "PDATA1"));
            }
            else
            {
                return (null);
            }

        }
        public int Get_Package_ID_PDATA1(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_Integer(this.Classifier_ID, database, "PDATA1", "t_object"));
            }
            else
            {
                return (0);
            }

        }
        public string Get_Classifier_Activity(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Classifier_Activity(database, this.Classifier_ID));
            }
            else
            {
                return (null);
            }

        }
        public string Get_Type_By_Classifier(Database database, string GUID)
        {
            if (GUID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String(GUID, database, "PDATA1"));
            }
            else
            {
                return (null);
            }

           
        }

        public int Get_Parent_ID(Database database)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_Integer(this.Classifier_ID, database, "ParentID", "t_object"));
            }
            else
            {
                return (-1);
            }
        }

        public string Get_GUID_By_ID(int ID, Database database)
        {
            this.ID = ID;
            if (this.ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_One_Attribut_String_by_ID(this.ID, database, "ea_guid"));
            }
            else
            {
                return (null);
            }

        }
        public int Get_Package_ID_by_Guid(Database database, string Package_GUID)
        {
            if (Package_GUID != null)
            {
                Interface_Package interface_Package = new Interface_Package();
                return (interface_Package.Get_One_Attribut_Integer(Package_GUID, database, "Package_ID"));
            }
            else
            {
                return (-1);
            }
        }
        public string Create_Package_Model(string Package_Name, EA.Repository Repository, Database database)
        {
            Interface_Package interface_Package = new Interface_Package();
            return(interface_Package.Create_Package_Model(database, Repository, Package_Name));
        }
        public string Create_Package(string Package_Name, EA.Package Parent, EA.Repository Repository, Database database)
        {
            Interface_Package interface_Package = new Interface_Package();
            return (interface_Package.Create_Package(database, Repository, Parent, Package_Name, false));
        }

        public string Create_Package_Create(string Package_Name, EA.Package Parent, EA.Repository Repository, Database database)
        {
            Interface_Package interface_Package = new Interface_Package();
            return (interface_Package.Create_Package(database, Repository, Parent, Package_Name, true));
        }
        public string Get_Parent_GUID(Database Data)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Parent_GUID(this.Classifier_ID, Data));
            }
            else
            {
                return (null);
            }
        }
        public List<string> Get_Children(Database database, List<string> m_Type_child, List<string> m_Stereotype_child)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Children(this.Classifier_ID, database, m_Type_child, m_Stereotype_child));
            }
            else
            {
                return (null);
            }
        }

        public List<string> Get_Generalization(Database database, List<string> m_Type_child, List<string> m_Stereotype_child, List<string> m_Type_Con, List<string> m_Stereotype_Con)
        {
            if (this.Classifier_ID != null)
            {
                List<string> m_supplier_guid = new List<string>();
                m_supplier_guid.Add(this.Classifier_ID);
                Interface_Connectors interface_Connectors = new Interface_Connectors();
                return (interface_Connectors.Get_Client_Element_By_Connector(database, m_supplier_guid, m_Type_child, m_Stereotype_child, m_Type_Con, m_Stereotype_Con));
            }
            else
            {
                return (null);
            }
        }

        public List<string> Get_Children_Guid(Database database, List<string> m_Type_child, List<string> m_Stereotype_child)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Children_Element(this.Classifier_ID, database, m_Type_child, m_Stereotype_child));
            }
            else
            {
                return (null);
            }
        }

        public List<string> Get_Children_Guid_Instanzen(Database database,string guid, List<string> m_Type_child, List<string> m_Stereotype_child)
        {
            if (guid != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Children_Element(guid, database, m_Type_child, m_Stereotype_child));
            }
            else
            {
                return (null);
            }
        }

        public List<string> Get_Parent_Taxonomy(Database database, string GUID, List<string> m_Type, List<string> m_Stereotype, List<string> m_Type_elem, List<string> m_Stereotype_elem)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Parent_Taxonomy(database, GUID, m_Type, m_Stereotype, m_Type_elem, m_Stereotype_elem));
            }
            else
            {
                return (null);
            }
        }


        public List<string> Get_Child_Taxonomy(Database database, string GUID, List<string> m_Type, List<string> m_Stereotype, List<string> m_Type_elem, List<string> m_Stereotype_elem)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Get_Children_Taxonomy(database, GUID, m_Type, m_Stereotype, m_Type_elem, m_Stereotype_elem));
            }
            else
            {
                return (null);
            }
        }
        private string Check_Element_Repository(Database Data, string Type, string StereoType, string Name, int ParentID)
        {
            if (this.Classifier_ID != null)
            {
                Interface_Element interface_Element = new Interface_Element();
                return (interface_Element.Check_Database_Element_Class(Data, Type, StereoType, Name, ParentID));
            }
            else
            {
                return (null);
            }

        }
        #endregion Attribute

        #region Misc
        private DateTime Get_DateTime()
        {
            DateTime now = DateTime.Now;

            return (now);
        }

        public void Set_Package( string Package_GUID, EA.Repository repository, Database database)
        {
            EA.Package package = repository.GetPackageByGuid(Package_GUID);


            Interface_Element interface_Element = new Interface_Element();

            interface_Element.Update_BigInt(this.Classifier_ID, package.PackageID, "Package_ID", database);
        }
        #endregion Misc

        #region TaggedValue

        public int Get_TV_Object_ID(Database database)
        {
            if(this.ID != null)
            {
                List<TV_Map> m_Get = new List<TV_Map>();
                Interface_TaggedValue interface_TaggedValue = new Interface_TaggedValue();
               
                m_Get.Add(new TV_Map("OBJECT_ID", OleDbType.VarChar, database.metamodel.Get_XAC_Import("OBJECT_ID"), "not set"));

                List<DB_Return> m_help = interface_TaggedValue.Get_Tagged_Value(m_Get, this.ID, database);

                if(m_help.Count > 0)
                {
                    if (m_help[0].Ret.Count > 1)
                    {
                        return (int.Parse(m_help[0].Ret[1].ToString()));
                    }
                }
            }


            return (-1);


        }

        public List<DB_Return> Get_TV_ret(List<DB_Insert> m_Insert, Database Data)
        {
            if (this.ID != null)
            {
                List<TV_Map> m_Get = new List<TV_Map>();
                //  string SQL = "SELECT Value, Notes FROM t_objectproperties WHERE Property = ? AND Object_ID = ?";
                //  string[] output = { "Value", "Notes" };
                Interface_TaggedValue interface_TaggedValue = new Interface_TaggedValue();


                if (m_Insert.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        m_Get.Add(new TV_Map(m_Insert[i1].Property, m_Insert[i1].oleDB_Type, Data.metamodel.Get_XAC_Import(m_Insert[i1].Property), (string)m_Insert[i1].Default_str));
                        i1++;
                    } while (i1 < m_Insert.Count);
                }

                return (interface_TaggedValue.Get_Tagged_Value(m_Get, this.ID, Data));
                //  OleDbCommand oleDbCommand = new OleDbCommand(SQL, Data.oLEDB_Interface.dbConnection);
                // return (Data.oLEDB_Interface.oleDB_SELECT_One_Table_Multiple_Property(oleDbCommand, output, m_Get, this.ID));
            }

            return (null);
        }

        public void Insert_TV(List<DB_Insert> m_Insert, Database Data, EA.Repository repository)
        {
            if (m_Insert.Count > 0)
            {
                string[] m_Input_Property = { "Object_ID", "Property", "Value", "Notes", "ea_guid" };
                TaggedValue tagged = new TaggedValue(Data.metamodel, Data);
                Interface_TaggedValue interface_TaggedValue = new Interface_TaggedValue();
                interface_TaggedValue.Insert_Tagged_Value(Data, m_Insert, tagged, this.ID, m_Input_Property);

                // Data.oLEDB_Interface.OLEDB_INSERT_One_Table_Multiple_TV(Data, m_Insert, tagged, "t_objectproperties", this.ID, m_Input_Property);
            }
        }

        public void Update_TV(List<DB_Insert> m_Insert, Database Data, EA.Repository repository)
        {
            if (this.ID != null)
            {
                //Checken ob vorhanden
                #region Check Upddate & Insert
                List<DB_Insert> m_Insert_new = new List<DB_Insert>();
                List<DB_Insert> m_Update_new = new List<DB_Insert>();
                List<TV_Map> m_Get = new List<TV_Map>();
                // string SQL = "SELECT Value, Notes FROM t_objectproperties WHERE Property = ? AND Object_ID = ?";
                // string[] output = { "Value", "Notes" };

                if (m_Insert.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        m_Get.Add(new TV_Map(m_Insert[i1].Property, m_Insert[i1].oleDB_Type, Data.metamodel.Get_XAC_Import(m_Insert[i1].Property), (string) m_Insert[i1].Default_str));
                        i1++;
                    } while (i1 < m_Insert.Count);
                }


                // OleDbCommand oleDbCommand = new OleDbCommand(SQL, Data.oLEDB_Interface.dbConnection);
                // List<DB_Return> m_TV = Data.oLEDB_Interface.oleDB_SELECT_One_Table_Multiple_Property(oleDbCommand, output, m_Get, this.ID);*/
                //Get_TV
                List<DB_Return> m_TV = this.Get_TV_ret(m_Insert, Data);

                //Überprüfen TV
                if (m_TV != null)
                {

                    if (m_TV.Count > 0)
                    {
                        int i2 = 0;
                        do
                        {

                            List<DB_Insert> m_help = m_Insert.Where(x => x.Property == m_TV[i2].Ret[0]).ToList();
                            if (m_TV[i2].Ret != null)
                            {
                                if (m_TV[i2].Ret.Count > 1 && m_help.Count > 0)
                                {
                                    if (m_help[0].oleDB_Type == OleDbType.VarChar)
                                    {
                                        if (m_help[0].Value_str != m_TV[i2].Ret[1])
                                        {
                                            if(m_TV[i2].Ret.Count > 2)
                                            {
                                                if(m_help[0].Value_str != m_TV[i2].Ret[2])
                                                {
                                                    m_Update_new.Add(m_help[0]);
                                                }
                                            }
                                            else
                                            {
                                                m_Update_new.Add(m_help[0]);
                                            }

                                            
                                        }
                                    }
                                }
                                else
                                {
                                    if (m_help.Count > 0)
                                    {
                                        m_Insert_new.Add(m_help[0]);
                                    }



                                }

                            }
                            else
                            {
                                if (m_help.Count > 0)
                                {
                                    m_Insert_new.Add(m_help[0]);
                                }
                            }
                            i2++;
                        } while (i2 < m_TV.Count);
                    }
                    else
                    {
                        m_Insert_new = m_Insert;
                    }

                    /*      var m_help = m_TV.Select(x => x.Ret[0]);
                          int i3 = 0;
                          do
                          {
                              if (m_help.Contains(m_Insert[i3]) == false && m_)
                              {

                              }

                              i3++;
                          } while (i3 < m_Insert.Count);
                          */
                }

                #endregion Check Update Und Insert

                #region Update 
                if (m_Update_new.Count > 0)
                {
                    Interface_TaggedValue interface_TaggedValue = new Interface_TaggedValue();
                    interface_TaggedValue.Update_Tagged_Value(m_Update_new, Data, this.ID);
                    //  string SQL_Update = "UPDATE t_objectproperties SET [Value] = ?, [Notes] = ? WHERE Object_ID = ? AND Property = ?";
                    //  Data.oLEDB_Interface.OLEDB_Update_One_Table_Multiple_TV(SQL_Update, m_Update_new, Data, this.ID);
                }

                #endregion Update


                #region Insert
                //Insert Befehl TV
                if (m_Insert_new.Count > 0)
                {
                    this.Insert_TV(m_Insert_new, Data, repository);
                }

                #endregion Insert
            }


        }
        #endregion TaggedValue

        #region Date
        public void Update_ModifiedDate(DateTime dateTime, EA.Repository repository)
        {
            //   EA.Element element = repository.GetElementByGuid(this.Classifier_ID);
            var SQL_Modified = "UPDATE t_object SET ModifiedDate = '" + DateTime.Now + "' WHERE ea_guid =  '" + this.Classifier_ID + "'";
            repository.Execute(SQL_Modified);
           
        }
        #endregion

        #region Archiv


        /* public List<string> Get_Child_Taxonomy(Database database, string GUID, List<string> m_Type, List<string> m_Stereotype, List<string> m_Type_elem, List<string> m_Stereotype_elem)
         {
             DB_Command command = new DB_Command();
             XML xML = new XML();
             List<string> m_Supplier_GUID = new List<string>();

             string SQL = "SELECT ea_guid FROM t_object WHERE Object_ID IN (SELECT Start_Object_ID FROM t_connector WHERE Connector_Type IN(" + command.Add_Parameters_Pre(m_Type.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype.ToArray()) + ") AND End_Object_ID IN (SELECT Object_ID FROM t_object WHERE Object_Type IN(" + command.Add_Parameters_Pre(m_Type_elem.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype_elem.ToArray()) + ") AND ea_guid = ?));";

             OleDbCommand SELECT1 = new OleDbCommand(SQL, database.oLEDB_Interface.dbConnection);

             List<DB_Input[]> ee = new List<DB_Input[]>();
             List<string> help_guid = new List<string>();
             help_guid.Add(GUID);

             ee.Add(m_Type_elem.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Stereotype_elem.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(help_guid.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Type.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Stereotype.Select(x => new DB_Input(-1, x)).ToArray());

             OleDbType[] m_input_Type = { OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar };
             database.oLEDB_Interface.Add_Parameters_Select(SELECT1, ee, m_input_Type);
             string[] m_output = { "ea_guid" };

             List<DB_Return> m_ret3 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT1, m_output);

             if (m_ret3[0].Ret.Count > 1)
             {
                 return (m_ret3[0].Ret.GetRange(1, m_ret3[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
             }
             else
             {
                 return (null);
             }
         }
         /*public List<string> Get_Parent_Taxonomy(Database database, string GUID, List<string> m_Type, List<string> m_Stereotype, List<string> m_Type_elem, List<string> m_Stereotype_elem)
         {
             DB_Command command = new DB_Command();
             XML xML = new XML();
             List<string> m_Supplier_GUID = new List<string>();

             string SQL = "SELECT ea_guid FROM t_object WHERE Object_ID IN (SELECT End_Object_ID FROM t_connector WHERE Connector_Type IN(" + command.Add_Parameters_Pre(m_Type.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype.ToArray()) + ") AND Start_Object_ID IN (SELECT Object_ID FROM t_object WHERE Object_Type IN(" + command.Add_Parameters_Pre(m_Type_elem.ToArray()) + ") AND Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype_elem.ToArray()) + ") AND ea_guid = ?));";

             OleDbCommand SELECT1 = new OleDbCommand(SQL, database.oLEDB_Interface.dbConnection);

             List<DB_Input[]> ee = new List<DB_Input[]>();
             List<string> help_guid = new List<string>();
             help_guid.Add(GUID);

             ee.Add(m_Type_elem.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Stereotype_elem.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(help_guid.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Type.Select(x => new DB_Input(-1, x)).ToArray());
             ee.Add(m_Stereotype.Select(x => new DB_Input(-1, x)).ToArray());

             OleDbType[] m_input_Type = { OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar };
             database.oLEDB_Interface.Add_Parameters_Select(SELECT1, ee, m_input_Type);
             string[] m_output = { "ea_guid" };

             List<DB_Return> m_ret3 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT1, m_output);

             if (m_ret3[0].Ret.Count > 1)
             {
                 return (m_ret3[0].Ret.GetRange(1, m_ret3[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
             }
             else
             {
                 return (null);
             }
         }
         /* public List<string> Get_Children(Database database, List<string> m_Type_child, List<string> m_Stereotype_child)
          {
              DB_Command command = new DB_Command();
              string SQL2 = "SELECT ea_guid FROM t_object WHERE Object_ID IN (SELECT Classifier FROM t_object WHERE Object_Type IN( " + command.Add_Parameters_Pre(m_Type_child.ToArray()) + ") AND Stereotype IN( " + command.Add_Parameters_Pre(m_Stereotype_child.ToArray()) + ") AND ParentID IN (SELECT Object_ID FROM t_object WHERE ea_guid = ?));";

              OleDbCommand SELECT1 = new OleDbCommand(SQL2, database.oLEDB_Interface.dbConnection);

              List<DB_Input[]> ee = new List<DB_Input[]>();
              List<string> help_guid = new List<string>();
              help_guid.Add(this.Classifier_ID);
              ee.Add(help_guid.Select(x => new DB_Input(-1, x)).ToArray());
              ee.Add(m_Type_child.Select(x => new DB_Input(-1, x)).ToArray());
              ee.Add(m_Stereotype_child.Select(x => new DB_Input(-1, x)).ToArray());


              OleDbType[] m_input_Type = { OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar, OleDbType.VarChar };
              database.oLEDB_Interface.Add_Parameters_Select(SELECT1, ee, m_input_Type);
              string[] m_output = { "ea_guid" };

              List<DB_Return> m_ret3 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT1, m_output);

              if (m_ret3[0].Ret.Count > 1)
              {
                  return (m_ret3[0].Ret.GetRange(1, m_ret3[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
              }
              else
              {
                  return (null);
              }
          }

          /// <summary>
          /// Anlegen eine PAckages
          /// </summary>
          /// <param name="Package_Name"></param>
          /// <param name="Repository"></param>
          /// <returns></returns>
          /*public string Create_Package_Model(string Package_Name, EA.Repository Repository)
          {
              XML Package_GUID = new XML();

              string SQL = @"SELECT ea_guid FROM t_object WHERE Name = '" + Package_Name + "' AND Object_Type = 'Package' AND ParentID = 0;";

              string xml_String = Repository.SQLQuery(SQL);


              List<string> help = Package_GUID.Xml_Read_Attribut("ea_guid", xml_String);

              if (help == null)
              {

                  EA.Package Model = Repository.Models.GetAt(0);

                  EA.Package Package = Model.Packages.AddNew(Package_Name, "Package");
                  Model.Packages.Refresh();
                  Package.Update();
                  Model.Update();
                  return (Package.PackageGUID);
              }
              else
              {

                  EA.Package Package = Repository.GetPackageByGuid(help[0]);
                  return (Package.PackageGUID);
              }
          }
          /* public string Get_Name_t_object_GUID(EA.Repository Repository, Database database)
           {
               if (this.Classifier_ID != null)
               {
                   // List<string> Name_List = new List<string>();
                   // XML XML_Name = new XML();
                   // Name_List = XML_Name.SQL_Query_Select(Repository, "ea_guid", this.Classifier_ID, "Name", "t_object", database);
                   // return (Name_List[0]);
                   return (this.Get_Name(database));
               }
               else
               {
                   return (null);
               }
           }
           */
        /*  public int Get_Package_ID(Database database)
          {
              XML xml = new XML();

              if (this.Classifier_ID != null)
              {
                  List<string> help = new List<string>();
                  help.Add(this.Classifier_ID);

                  List<DB_Input[]> ee = new List<DB_Input[]>();
                  ee.Add(help.Select(x => new DB_Input(-1, x)).ToArray());
                  string[] m_output = { "Package_ID" };
                  string table = "t_object";
                  string[] m_input_Property = { "ea_guid" };
                  OleDbType[] m_input_Type = { OleDbType.VarChar };

                  List<DB_Return> m_ret = xml.Read_Attribut(m_output, table, m_input_Property, ee, m_input_Type, database);

                  if (m_ret[0].Ret.Count > 1)
                  {
                      return ((int)m_ret[0].Ret[1]);
                  }
                  else
                  {
                      return (-1);
                  }
              }

              return (-1);

          }
          */
        /*public int Get_Parent_ID(Database database)
        {
            XML xml = new XML();

            if (this.Classifier_ID != null)
            {
                List<string> help = new List<string>();
                help.Add(this.Classifier_ID);

                List<DB_Input[]> ee = new List<DB_Input[]>();
                ee.Add(help.Select(x => new DB_Input(-1, x)).ToArray());
                string[] m_output = { "ParentID" };
                string table = "t_object";
                string[] m_input_Property = { "ea_guid" };
                OleDbType[] m_input_Type = { OleDbType.VarChar };

                List<DB_Return> m_ret = xml.Read_Attribut(m_output, table, m_input_Property, ee, m_input_Type, database);

                if (m_ret[0].Ret.Count > 1)
                {
                    return ((int)m_ret[0].Ret[1]);
                }
                else
                {
                    return (-1);
                }
            }

            retur*/

        /*  public string Get_GUID_By_ID(int ID, Database database)
          {
              XML xml = new XML();
              List<DB_Input[]> ee = new List<DB_Input[]>();
              List<int> help_ID = new List<int>();
              help_ID.Add(ID);
              ee.Add(help_ID.Select(x => new DB_Input(x, null)).ToArray());

              string[] m_output = { "ea_guid" };
              string table = "t_object";
              string[] m_input_Property = { "Object_ID" };
              OleDbType[] m_input_Type = { OleDbType.BigInt };

              List<DB_Return> m_ret = xml.Read_Attribut(m_output, table, m_input_Property, ee, m_input_Type, database);

              if (m_ret[0].Ret.Count > 1)
              {
                  this.Classifier_ID = m_ret[0].Ret[1].ToString();
                  return (m_ret[0].Ret[1].ToString());
              }
              else
              {
                  return (null);
              }

          }*/
        /* public int Get_Package_ID_by_Guid(Database database, string Package_GUID)
         {
             XML xml = new XML();

             List<string> help = new List<string>();
             help.Add(Package_GUID);



             List<DB_Input[]> ee = new List<DB_Input[]>();
             ee.Add(help.Select(x => new DB_Input(-1, x)).ToArray());
             string[] m_output = { "Package_ID" };
             string table = "t_package";
             string[] m_input_Property = { "ea_guid" };
             OleDbType[] m_input_Type = { OleDbType.VarChar };

             List<DB_Return> m_ret = xml.Read_Attribut(m_output, table, m_input_Property, ee, m_input_Type, database);

             if (m_ret[0].Ret.Count > 1)
             {
                 return ((int)m_ret[0].Ret[1]);
             }
             else
             {
                 return (-1);
             }
         }*/
        /* public string Get_Parent_GUID(Database Data)
         {
             if (this.Classifier_ID != null && this.Classifier_ID != "")
             {

                 XML Parent_ID = new XML();
                 int ret = 0;

                 string SQL = "SELECT ea_guid FROM t_object WHERE Object_ID IN( SELECT ParentID FROM t_object WHERE ea_guid = ?);";

                 OleDbCommand SELECT = new OleDbCommand(SQL, Data.oLEDB_Interface.dbConnection);

                 List<DB_Input[]> ee = new List<DB_Input[]>();
                 List<string> help_guid = new List<string>();
                 help_guid.Add(this.Classifier_ID);
                 ee.Add(help_guid.Select(x => new DB_Input(-1, x)).ToArray());

                 OleDbType[] m_input_Type = { OleDbType.VarChar };
                 Data.oLEDB_Interface.Add_Parameters_Select(SELECT, ee, m_input_Type);
                 string[] m_output = { "ea_guid" };

                 List<DB_Return> m_ret = Data.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT, m_output);

                 if (m_ret[0].Ret.Count > 1)
                 {
                     //List<string> help = m_ret4[0].Ret.GetRange(1, m_ret4[0].Ret.Count - 1);
                     return (m_ret[0].Ret[1].ToString());
                 }
                 else
                 {
                     return (null);
                 }
             }
             else
             {
                 return (null);
             }


         }
         */
        #endregion Archiv
    }//end Repository_Element



}//end namespace Requirement_Plugin