///////////////////////////////////////////////////////////
//  Repository_Elements.cs
//  Implementation of the Class Repository_Elements
//  Generated by Enterprise Architect
//  Created on:      14-Jan-2019 17:01:23
//  Original author: Yannick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Forms;
using System.Xml;
using System.Linq;
using System.Data.OleDb;
using Requirement_Plugin.Interfaces;
using System.Data.Odbc;

using Database_Connection;
using Elements;
using Requirement_Plugin;
using Requirements;
using Forms;

using System.Threading.Tasks;
using Ennumerationen;

namespace Repsoitory_Elements
{
	/// <summary>
	/// Collection von Repository_Elements
	/// </summary>
	public class Repository_Elements {
		public List<Stakeholder> m_Child;
		public List<Element_User> m_Element_User;
		public Stakeholder Parent;


		public Repository_Elements(){

		}

		~Repository_Elements(){

		}
        #region Get_Elements

        public List<string> Get_Diagram_By_Package(Database database, List<int> m_Package_ID)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_m_Attribut_By_m_Attribut_Integer(database, m_Package_ID, "Package_ID", "ea_guid", "t_diagram"));
        }

        public List<Repository_Element> Get_All_Elements(Database database, List<string> m_Type, List<string> m_Stereotype)
        {
            List<Repository_Element> repository_Elements  = new List<Repository_Element>();
            Interface_Collection interface_Collection = new Interface_Collection();

            List<string> m_guid = interface_Collection.Get_Elements_GUID(database, m_Type, m_Stereotype);

            if(m_guid != null)
            {
                if (m_guid.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        //Repository_Element anlegen
                        Repository_Element repository_Element = new Repository_Element();
                        //Classifier festlegen
                        repository_Element.Classifier_ID = m_guid[i1];
                        //Id erhalten
                        repository_Element.ID = repository_Element.Get_Object_ID(database);

                        repository_Elements.Add(repository_Element);

                        i1++;
                    } while (i1 < m_guid.Count);

                }
            }

           


            return (repository_Elements);
        }

        public List<Repository_Element> Get_All_Elements_Requirement(Database database, List<string> m_Type, List<string> m_Stereotype)
        {
            List<Repository_Element> repository_Elements = new List<Repository_Element>();
            Interface_Collection_Requirements interface_Collection = new Interface_Collection_Requirements();

            List<string> m_guid = interface_Collection.Get_Elements_GUID(database, m_Type, m_Stereotype);

            if(m_guid != null)
            {
                if (m_guid.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        //Repository_Element anlegen
                        Repository_Element repository_Element = new Repository_Element();
                        //Classifier festlegen
                        repository_Element.Classifier_ID = m_guid[i1];
                        //Id erhalten
                        repository_Element.ID = repository_Element.Get_Object_ID(database);

                        repository_Elements.Add(repository_Element);

                        i1++;
                    } while (i1 < m_guid.Count);

                }
            }

            


            return (repository_Elements);
        }
        public void Test(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            interface_Collection.Test(database);
        }
        public Logical Get_All_Szenar(Database database, EA.Repository repository)
        {
            //Gesamt Szenar erhalten
            Logical m_Logical_1 = null;
            Repository_Element repository_element = new Repository_Element();

            List<string> m_Logical_Guids = this.Get_Logicals_GUID2(database);

            if(m_Logical_Guids != null)
            {
                int i2 = 0;
                do
                {
                    Logical recent = new Logical(m_Logical_Guids[i2], database);

                    if(recent.Name == database.metamodel.m_Szenar[0].DefaultName)
                    {
                        m_Logical_1 = recent;
                        i2 = m_Logical_Guids.Count;
                    }

                    i2++;
                } while (i2 < m_Logical_Guids.Count);
            }

            if(m_Logical_1 != null)
            {
                List<string> m_Type = database.metamodel.m_Elements_Usage.Select(x => x.Type).ToList() ;
                List<string> m_Stereotype = database.metamodel.m_Elements_Usage.Select(x => x.Stereotype).ToList();


                List<string> m_Children_GUID = m_Logical_1.Get_Children_Guid(database, m_Type, m_Stereotype);

                if(m_Children_GUID != null)
                {
                    int i1 = 0;
                    do
                    {
                        repository_element.Classifier_ID = m_Children_GUID[i1];
                        string Classifier = repository_element.Get_Classifier(database);

                        if(Classifier != null)
                        {
                            NodeType recent_nt = new NodeType(Classifier, repository, database);
                            recent_nt.ID = repository_element.Get_Object_ID(database);
                            recent_nt.Instantiate_GUID = m_Children_GUID[i1];
                            recent_nt.Get_TV_Instantiate(database, repository);
                          //  recent_nt.ID = recent_nt.Get

                            recent_nt.Get_Children_Part(m_Children_GUID[i1], database, repository);

                            m_Logical_1.m_NodeType.Add(recent_nt);
                        }

                       

                        i1++;
                    } while (i1 < m_Children_GUID.Count);
                }

                return (m_Logical_1);

            }
            else
            {
                return (null);
            }

        }

        public void Get_MeasurementType_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Measurementype(database);

            if (m_guid != null)
            {
                Parallel.ForEach(m_guid, guid =>
                {
                    Requirement_Plugin.Repository_Elements.MeasurementType recent = new Requirement_Plugin.Repository_Elements.MeasurementType(guid, database);

                    if (database.m_MeasurementType.Contains(recent) == false)
                    {
                        database.m_MeasurementType.Add(recent);
                    }
                });
            }
        }

        public List<string> Get_Measurementype(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Measurement_Type.Select(x => x.Type).ToList(), database.metamodel.m_Measurement_Type.Select(x => x.Stereotype).ToList()));

        }

        public void Get_NodeTypes_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_NodeTypes(database);

            

            if (m_guid != null)
            {
                load.progressBar1.Maximum = 4;
                load.label_Progress.Text = "Anlegen NodeType";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen
               /* int i1 = 0;
                do
                {

                    NodeType recent = new NodeType(m_guid[i1], repository, database);
                    recent.Instantiate_GUID = m_guid[i1];
                    database.m_NodeType.Add(recent);

                    i1++;
                } while (i1 < m_guid.Count);
               */
               Parallel.ForEach(m_guid, guid =>
                {
                    NodeType recent = new NodeType(guid, repository, database);
                    recent.Instantiate_GUID = guid;
                    database.m_NodeType.Add(recent);

                   
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
                //Dekomposition erzeugen
                Parallel.ForEach(database.m_NodeType, nodetype =>
                {

                    nodetype.Get_Children_Class(database, repository);

                    
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
                //Generalisierung
                Parallel.ForEach(database.m_NodeType, nodetype =>
                {

                    nodetype.Check_Generalization(database);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
               
            }

        }

        public void Get_NodeTypes_reduced_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_NodeTypes(database);



            if (m_guid != null)
            {
                load.progressBar1.Maximum = 1;
                load.label_Progress.Text = "Anlegen NodeType";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen

                int i1 = 0;
                do
                {

                    NodeType recent = new NodeType(null, null, null);
                    recent.Classifier_ID = m_guid[i1];
                    recent.Instantiate_GUID = m_guid[i1];
                    recent.Get_TV_reduced(database, repository);
                    database.m_NodeType.Add(recent);

                    i1++;
                } while (i1 < m_guid.Count);

             /*   Parallel.ForEach(m_guid, guid =>
                {
                    NodeType recent = new NodeType(null, null, null);
                    recent.Classifier_ID = guid;
                    recent.Instantiate_GUID = guid;
                    recent.Get_TV_reduced(database, repository);
                    database.m_NodeType.Add(recent);


                });
             */
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
               
            }

        }
        public List<string> Get_NodeTypes(Database database)
        {
            return (this.Get_NodeTypes_string(database));
        }

        private List<string> Get_NodeTypes_string( Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Elements_OpArch_Definition.Select(x => x.Type).ToList(), database.metamodel.m_Elements_OpArch_Definition.Select(x => x.Stereotype).ToList()));
        }
        public List<int> Get_NodeTypes_ID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_ID(database, database.metamodel.m_Elements_OpArch_Definition.Select(x => x.Type).ToList(), database.metamodel.m_Elements_OpArch_Definition.Select(x => x.Stereotype).ToList()));
        }

        public void Get_Systemelemente_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_SysElemente(database);

           

            if (m_guid != null)
            {
                load.progressBar1.Maximum = 3;
                load.label_Progress.Text = "Anlegen Systemelemente";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen
                Parallel.ForEach(m_guid, guid =>
                {
                    SysElement recent = new SysElement(guid, repository, database);
                    recent.Instantiate_GUID = guid;
                    database.m_SysElemente.Add(recent);

                    recent.Get_Sys_StereoType_Import(database);

                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
                //Dekomposition erzeugen
                Parallel.ForEach(database.m_SysElemente, nodetype =>
                {

                    nodetype.Get_Children_Class(database, repository);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
                //Generalisierung
                Parallel.ForEach(database.m_SysElemente, nodetype =>
                {

                    nodetype.Check_Generalization_SysElem(database);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
            }
        }

        public void Get_Systemelemente_reduced_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_SysElemente(database);



            if (m_guid != null)
            {
                load.progressBar1.Maximum = 1;
                load.label_Progress.Text = "Anlegen NodeType";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen
                Parallel.ForEach(m_guid, guid =>
                {
                    SysElement recent = new SysElement(guid, repository, database);
                    recent.Classifier_ID = guid;
                    recent.Instantiate_GUID = guid;
                    recent.Get_TV_reduced(database, repository);
                    database.m_SysElemente.Add(recent);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }

        }
        public List<string> Get_SysElemente(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Elements_SysArch_Definition.Select(x => x.Type).ToList(), database.metamodel.m_Elements_SysArch_Definition.Select(x => x.Stereotype).ToList()));
        }

        public List<int> Get_SysElemente_ID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_ID(database, database.metamodel.m_Elements_SysArch_Definition.Select(x => x.Type).ToList(), database.metamodel.m_Elements_SysArch_Definition.Select(x => x.Stereotype).ToList()));
        }

        #region Nachweisarten
        public void Get_Nachweisarten_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Nachweisarten(database);



            if (m_guid != null)
            {
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Anlegen Nachweisarten";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen
                Parallel.ForEach(m_guid, guid =>
                {
                    Nachweisart recent = new Repsoitory_Elements.Nachweisart(guid, database, repository);
                   
                    database.m_Nachweisarten.Add(recent);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();
               
            }
        }
        public List<string> Get_Nachweisarten(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Nachweisart.Select(x => x.Type).ToList(), database.metamodel.m_Nachweisart.Select(x => x.Stereotype).ToList()));
        }
        #endregion
        #region Abnahmekriteriuem
        public void Get_Abnahemkriterium_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Abnahemkriterium(database);



            if (m_guid != null)
            {
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Anlegen Abnahmekriterien";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType erzeugen
                Parallel.ForEach(m_guid, guid =>
                {
                    Abnahmekriterium recent = new Repsoitory_Elements.Abnahmekriterium(guid, database, repository);

                    database.m_Abnahmekriterium.Add(recent);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }
        }
        public List<string> Get_Abnahemkriterium(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Abnahmekriterium.Select(x => x.Type).ToList(), database.metamodel.m_Abnahmekriterium.Select(x => x.Stereotype).ToList()));
        }
        #endregion
        public void Get_InformationElement_Parallel(Database database, EA.Repository Repository)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            bool save = database.metamodel.flag_Analyse_Diagram;
            database.metamodel.flag_Analyse_Diagram = false;
            List<string> m_ret = (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_InformationItem.Select(x => x.Type).ToList(), database.metamodel.m_InformationItem.Select(x => x.Stereotype).ToList()));
            database.metamodel.flag_Analyse_Diagram = save;

            List<InformationElement> m_InformationElement = new List<InformationElement>();
            //MessageBox.Show(m_Capability_GUID.Count.ToString());

            if(m_ret != null)
            {
                //Capability anlegen
                Parallel.ForEach(m_ret, guid =>
                {
                    InformationElement recent = new InformationElement(guid, database);
                    m_InformationElement.Add(recent);

                });
                database.m_InformationElement = m_InformationElement;
            }

         
        }

        public List<string> Get_Information_Element(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            bool save = database.metamodel.flag_Analyse_Diagram;
            database.metamodel.flag_Analyse_Diagram = false;
            List<string> m_ret = (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_InformationItem.Select(x => x.Type).ToList(), database.metamodel.m_InformationItem.Select(x => x.Stereotype).ToList()));
            database.metamodel.flag_Analyse_Diagram = save;
            return (m_ret);
        }
        public List<string> Get_Capability_GUID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            bool save = database.metamodel.flag_Analyse_Diagram;
            database.metamodel.flag_Analyse_Diagram = false;
            List<string> m_ret = (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Capability.Select(x => x.Type).ToList(), database.metamodel.m_Capability.Select(x => x.Stereotype).ToList()));
            database.metamodel.flag_Analyse_Diagram = save;
            return (m_ret);
        }

        public void Get_Capability (List<string> m_Capability_GUID, Database database, Loading_OpArch Load, EA.Repository Repository, TaggedValue Tagged)
        {
            if (m_Capability_GUID != null)
            {
                List<Capability> m_Capability = new List<Capability>();
                //MessageBox.Show(m_Capability_GUID.Count.ToString());

                Load.label_Progress.Text = "Anlegen Capability";
                Load.progressBar1.Maximum = 2 * m_Capability_GUID.Count;
                Load.progressBar1.Value = 0;
                Load.Refresh();

                //Alle Capability anlegen
                int c1 = 0;
                do
                {
                    Capability recent_cap = new Capability(m_Capability_GUID[c1], Repository, database);

                    m_Capability.Add(recent_cap);


                    c1++;

                    Load.progressBar1.PerformStep();
                    Load.Refresh();

                } while (c1 < m_Capability_GUID.Count);

                database.m_Capability = m_Capability;
                //MessageBox.Show("Anz Cap: " +m_Capability.Count);
                //Beziehung unter den Capability anlegen
                c1 = 0;
                do
                {
                    m_Capability[c1].Get_Parent(database, Repository);
                    m_Capability[c1].Get_Child(database, Repository);

                    if (Tagged.Get_Tagged_Value(m_Capability[c1].Classifier_ID, "SYS_AG_ID", Repository) == null || Tagged.Get_Tagged_Value(m_Capability[c1].Classifier_ID, "SYS_AG_ID", Repository) == "kein")
                    {
                        Tagged.Insert_Tagged_Value(m_Capability[c1].Classifier_ID, "SYS_AG_ID", database.metamodel.m_Header_agid[2] + " " + (c1 + 1).ToString(), null, Repository);
                    }

                    c1++;
                    Load.progressBar1.PerformStep();
                    Load.Refresh();

                } while (c1 < m_Capability.Count);


            }
        }

        public void Get_Capability_Parallel(Database database, EA.Repository Repository)
        {
            TaggedValue Tagged = new TaggedValue(database.metamodel, database);
            List<string> m_Capability_GUID = this.Get_Capability_GUID( Repository, database);

            if (m_Capability_GUID != null)
            {
                List<Capability> m_Capability = new List<Capability>();
                //MessageBox.Show(m_Capability_GUID.Count.ToString());

               

                //Capability anlegen
                Parallel.ForEach(m_Capability_GUID, guid =>
                {
                    Capability recent_cap = new Capability(guid, Repository, database);
                    m_Capability.Add(recent_cap);

                });
                database.m_Capability = m_Capability;
                //Konnektoren anlegen
                var lauf = 0;

                Parallel.ForEach(database.m_Capability, capability =>
                {
                    if(capability != null)
                    {
                        capability.Get_Parent(database, Repository);
                        capability.Get_Child(database, Repository);

                        if (Tagged.Get_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", Repository) == null || Tagged.Get_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", Repository) == "kein")
                        {
                            Tagged.Insert_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", database.metamodel.m_Header_agid[2] + " " + (lauf + 1).ToString(), null, Repository);
                        }
                        lauf++;
                    }
                   
                });
              
            }
        }

        #region Catalogue
        public void Get_CatalogueParallel(Database database, EA.Repository Repository)
        {
            TaggedValue Tagged = new TaggedValue(database.metamodel, database);
            List<string> m_Capability_GUID = this.Get_Catalogue_GUID(Repository, database);

            if (m_Capability_GUID != null)
            {
                List<Requirement_Plugin.Repository_Elements.Catalogue> m_Capability = new List<Requirement_Plugin.Repository_Elements.Catalogue>();
                //MessageBox.Show(m_Capability_GUID.Count.ToString());



                //Capability anlegen
                Parallel.ForEach(m_Capability_GUID, guid =>
                {
                    Requirement_Plugin.Repository_Elements.Catalogue recent_cap = new Requirement_Plugin.Repository_Elements.Catalogue(guid, Repository, database);
                    m_Capability.Add(recent_cap);

                });
                database.m_Catalogue = m_Capability;
                //Konnektoren anlegen
                var lauf = 0;

                Parallel.ForEach(database.m_Catalogue, capability =>
                {
                    capability.Get_Parent(database, Repository);
                    capability.Get_Child_Catalogue(database, Repository);

                    if (Tagged.Get_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", Repository) == null || Tagged.Get_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", Repository) == "kein")
                    {
                        Tagged.Insert_Tagged_Value(capability.Classifier_ID, "SYS_AG_ID", database.metamodel.m_Header_agid[2] + " " + (lauf + 1).ToString(), null, Repository);
                    }
                    lauf++;
                });

            }
        }
        public List<string> Get_Catalogue_GUID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            bool save = database.metamodel.flag_Analyse_Diagram;
            database.metamodel.flag_Analyse_Diagram = false;
            List<string> m_ret = (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Capability_Catalogue.Select(x => x.Type).ToList(), database.metamodel.m_Capability_Catalogue.Select(x => x.Stereotype).ToList()));
            database.metamodel.flag_Analyse_Diagram = save;
            return (m_ret);
        }
        #endregion Catalogue
        public Requirement_Plugin.Repository_Elements.Catalogue Get_Capability_Catalogue(Database database, EA.Repository Repository, string guid)
        {
            Requirement_Plugin.Repository_Elements.Catalogue recent_catalogue = new Requirement_Plugin.Repository_Elements.Catalogue(guid, Repository, database);

            recent_catalogue.Get_Child_Catalogue(database, Repository);


            return (recent_catalogue);
        }


        public List<string> Get_Logicals_GUID2(Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Szenar.Select(x => x.Type).ToList(), database.metamodel.m_Szenar.Select(x => x.Stereotype).ToList()));
        }

        public void Get_Logicals_Parallel(Database database)
        {
            List<string> m_Logical_Guids = this.Get_Logicals_GUID2(database);
            List<Logical> m_Logcal = new List<Logical>();

            if(m_Logical_Guids != null)
            {
                if (m_Logical_Guids.Count > 0)
                {
                    /*  int i1 = 0;
                      do
                      {
                          Logical logical = new Logical(m_Logical_Guids[i1], database);

                          if (database.metamodel.m_Szenar.Select(x => x.DefaultName).ToList().Contains(logical.Get_Name(database)) == false)
                          {
                              m_Logcal.Add(logical);
                          }

                          i1++;
                      } while (i1 < m_Logical_Guids.Count);
                    
                    */
                    database.SQLITE_Interface.db_Close();

                    Parallel.ForEach(m_Logical_Guids, guid =>
                    {
                        bool flag = false;

                        //do
                        //{
                          // if(database.SQLITE_Interface.dbConnection.State == System.Data.ConnectionState.Closed)
                            //{
                              //  database.SQLITE_Interface.db_Open();
                              //  flag = true;

                                Logical logical = new Logical(guid, database);
                                if (database.metamodel.m_Szenar.Select(x => x.DefaultName).ToList().Contains(logical.Get_Name(database)) == false)
                                {
                                    m_Logcal.Add(logical);
                                }

                                //database.SQLITE_Interface.db_Close();
                            //}

                        //} while (flag == false);

                       
                    });
                   
                    database.m_Logical = m_Logcal;

                    Parallel.ForEach(database.m_Logical, logical =>
                    {
                        logical.Check_Generalization(database);
                    });

                   
                }
            }

           

            /*  List<string> m_Logical_Guids = new List<string>();
              List<Logical> m_Logcal = new List<Logical>();
              m_Logical_Guids = this.Get_Logicals_GUID2(database);

              if(m_Logical_Guids != null)
              {
                  int i1 = 0;
                  do
                  {
                      Logical logical = new Logical(m_Logical_Guids[i1], database);
                      if(database.metamodel.m_Szenar.Select(x => x.DefaultName).ToList().Contains(logical.Get_Name(database)) == false)
                      {
                          m_Logcal.Add(logical);
                      }

                      i1++;
                  } while (i1 < m_Logical_Guids.Count);


                 //database.m_Logical = m_Logcal;


              }

              if(m_Logcal.Count  == 0)
              {
                  m_Logcal = null;
              }

              return (m_Logcal);
            */
        }

        public void Get_Stakeholder_Parallel(EA.Repository repository, Database database)
        {
            List<string> m_guid = this.Get_Stakeholder_GUID(repository, database);

            if (m_guid != null)
            {

                Parallel.ForEach(m_guid, guid =>
                {
                    Stakeholder recent_st = new Stakeholder(guid, repository, database);

                    database.m_Stakeholder.Add(recent_st);
                });
               /* int s1 = 0;
                do
                {
                    Stakeholder recent_st = new Stakeholder(m_st_guid[s1], repository, Data);

                    Data.m_Stakeholder.Add(recent_st);

                    s1++;
                } while (s1 < m_st_guid.Count);*/
            }
        }

        public List<string> Get_Stakeholder_GUID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_Stakeholder_Definition.Select(x => x.Type).ToList(), database.metamodel.m_Stakeholder_Definition.Select(x => x.Stereotype).ToList()));
        }
        public List<string> Get_CapConf_GUID(EA.Repository Repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Elements_GUID(database, database.metamodel.m_CapConf.Select(x => x.Type).ToList(), database.metamodel.m_CapConf.Select(x => x.Stereotype).ToList()));
        }
        public List<string> Get_Activity_GUID(EA.Repository repository, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            List<string> m_Type_Activity = database.metamodel.m_Aktivity_Definition.Select(x => x.Type).ToList();
            List<string> m_Stereotype_Activity = database.metamodel.m_Aktivity_Definition.Select(x => x.Stereotype).ToList();
            List<string> m_Type_Action = database.metamodel.m_Aktivity_Usage.Select(x => x.Type).ToList();
            List<string> m_Stereotype_Action = database.metamodel.m_Aktivity_Usage.Select(x => x.Stereotype).ToList();
            return (interface_Collection.Get_Activity_GUID(database, m_Type_Activity, m_Stereotype_Activity, m_Type_Action, m_Stereotype_Action));
        }

        public List<Activity> Get_Activity(EA.Repository repository, Database database)
        {
            List<Activity> m_ret = new List<Activity>();

            List<string> m_GUID = Get_Activity_GUID( repository,  database);

            if(m_GUID != null)
            {
                if(m_GUID.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        Activity activity = new Activity(m_GUID[i1], database, repository);

                        m_ret.Add(activity);

                        i1++;
                    } while (i1 < m_GUID.Count);
                }

            }


            return (m_ret);
        }

        public void Get_Activity_Parallel(Database database, EA.Repository repository)
        {
            List<Activity> m_ret = new List<Activity>();

            List<string> m_GUID = Get_Activity_GUID(repository, database);


            if (m_GUID != null)
            {
                if (m_GUID.Count > 0)
                {
                   /* int i1 = 0;
                    do
                    {
                        Activity activity = new Activity(m_GUID[i1], database, repository);

                        database.m_Activity.Add(activity);

                        i1++;
                    } while (i1 < m_GUID.Count);
                   */

                    Parallel.ForEach(m_GUID, guid =>
                    {
                       Activity activity = new Activity(guid, database, repository);

                       database.m_Activity.Add(activity);
                   });

                    Parallel.ForEach(database.m_Activity, activity =>
                    {
                        activity.Check_Children(repository, database);
                    });

                    Parallel.ForEach(database.m_Activity, activity =>
                    {
                        activity.Check_Generalization(repository, database);
                    });
                }
            }
        }

        public List<string> Get_Stereotpye_Requirements(List<string> m_Type, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_m_Attribut_By_m_Attribut(database, m_Type, "Object_Type", "Stereotype", "t_object"));
        }

        public List<string> Get_Requirements_GUID(Database Data,List<string> m_Type, List<string> m_Stereotype)
        {
           
            Interface_Collection_Requirements interface_Collection = new Interface_Collection_Requirements();

            List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            return (m_Guid);
        }

        public List<string> Get_Requirements_GUID2(Database Data, List<string> m_Type, List<string> m_Stereotype)
        {

            Interface_Collection interface_Collection = new Interface_Collection();

            List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            return (m_Guid);
        }

        public List<string> Get_Stereotypes(List<string> m_guid, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_m_Attribut_By_m_Attribut(database, m_guid, "ea_guid", "Stereotype", "t_object"));
        }

        public List<string> Get_Stereotypes2(List<string> m_guid, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_Stereotype_By_Type_AND_GUID(database, m_guid));
        }

        public List<string> Get_Elements_NotPackage(List<string> m_guid, List<int> m_package_id,  Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_By_NOT_PackageID(database, m_guid, m_package_id));
        }

        public List<string> Get_Elements_GUID_Stereotype(List<string> m_guid, string stereotype, Database database)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Get_GUID_By_Stereotype_AND_GUID(database, m_guid, stereotype));
        }

        public void Get_Requirements_Parallel(Database Data, EA.Repository repository, List<string> m_Stereotype, List<string> m_Type, Loading_OpArch load)
        {
            List<Requirement> m_Requirement = new List<Requirement>();
            //Interface_Collection interface_Collection = new Interface_Collection();
            //List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            List<string> m_Guid = Get_Requirements_GUID(Data, m_Type, m_Stereotype);

            if (m_Guid != null)
            {
              
                Parallel.ForEach(m_Guid, guid =>
                {
                    Requirement recent = new Requirement(guid, Data.metamodel);
                    recent.Get_Tagged_Values_From_Requirement(guid, repository, Data);
                    m_Requirement.Add(recent);
                });

                Data.m_Requirement = m_Requirement;

                //Konnektoren erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Requirement 0";
                load.progressBar1.Maximum = Data.m_Requirement.Count;
                load.progressBar1.Value = 0;
                load.Update();
                load.Refresh();
                int lauf = 0;
              /*  Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Get_Connector_Requirements(Data, repository);
                    lauf++;
                    load.label_Progress.Text = "Get Konnektor Requirement "+lauf;
                    load.Update();
                    load.Refresh();

                });*/
                if (Data.m_Requirement.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        Data.m_Requirement[i1].Get_Connector_Requirements(Data, repository);
                        lauf++;
                        load.label_Progress.Text = "Get Konnektor Requirement " + lauf;
                        load.progressBar1.PerformStep();
                        load.Update();
                        load.Refresh();

                        i1++;
                    } while (i1 < Data.m_Requirement.Count);
                }
                //RequirementsCategory erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor RequirmentCategory";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Check_Capability(repository, Data);
                });
                //Szenar erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Szenar";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    if(Data.metamodel.modus == 0)
                    {
                        requirement.Get_Logical(Data);
                    }
                    else
                    {
                        requirement.Get_Logical(Data);
                        // requirement.Get_Logical_SysElem(Data);
                    }
                    
                });
                //NodeType erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor NodeType";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Get_System(Data, repository);
                });
                //SysElement erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Systemelement";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Get_SysElement(Data, repository);
                });
                //SysElement Realisierung erhalten
                //Requirements der Realisierungsphase Realisierungs SysElem erhalten
                List<Requirements.Requirement> m_Req_Real = Data.m_Requirement.Where(x => x.AFO_CPM_PHASE == AFO_CPM_PHASE.Drei).ToList();
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Systemelement Realisierung";
                load.Update();
                load.Refresh();
                Parallel.ForEach(m_Req_Real, requirement =>
                {
                    requirement.Get_SysElement_Realisierung(Data, repository);
                });
            }
        }

        public void Get_Requirements_Parallel_PFK(Database Data, EA.Repository repository, List<string> m_Stereotype, List<string> m_Type, Loading_OpArch load)
        {
            List<Requirement> m_Requirement = new List<Requirement>();
            //Interface_Collection interface_Collection = new Interface_Collection();
            //List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            List<string> m_Guid = Get_Requirements_GUID(Data, m_Type, m_Stereotype);

            if (m_Guid != null)
            {

                Parallel.ForEach(m_Guid, guid =>
                {
                    Requirement recent = new Requirement(guid, Data.metamodel);
                    recent.Get_Tagged_Values_From_Requirement(guid, repository, Data);
                    m_Requirement.Add(recent);
                });

                Data.m_Requirement = m_Requirement.Where(x => x.AFO_CPM_PHASE == Ennumerationen.AFO_CPM_PHASE.Eins).ToList();

                //Konnektoren erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Requirement 0";
                load.progressBar1.Maximum = Data.m_Requirement.Count;
                load.progressBar1.Value = 0;
                load.Update();
                load.Refresh();
                int lauf = 0;
                /*  Parallel.ForEach(Data.m_Requirement, requirement =>
                  {
                      requirement.Get_Connector_Requirements(Data, repository);
                      lauf++;
                      load.label_Progress.Text = "Get Konnektor Requirement "+lauf;
                      load.Update();
                      load.Refresh();

                  });*/
                if (Data.m_Requirement.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        Data.m_Requirement[i1].Get_Connector_Requirements(Data, repository);
                        lauf++;
                        load.label_Progress.Text = "Get Konnektor Requirement " + lauf;
                        load.progressBar1.PerformStep();
                        load.Update();
                        load.Refresh();

                        i1++;
                    } while (i1 < Data.m_Requirement.Count);
                }
                //RequirementsCategory erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor RequirmentCategory";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Check_Capability(repository, Data);
                });
                //Szenar erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Szenar";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    if (Data.metamodel.modus == 0)
                    {
                        requirement.Get_Logical(Data);
                    }
                    else
                    {
                        requirement.Get_Logical(Data);
                        // requirement.Get_Logical_SysElem(Data);
                    }

                });
                //NodeType erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor NodeType";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Get_System(Data, repository);
                });
                //SysElement erhalten
                load.progressBar1.PerformStep();
                load.label_Progress.Text = "Get Konnektor Systemelement";
                load.Update();
                load.Refresh();
                Parallel.ForEach(Data.m_Requirement, requirement =>
                {
                    requirement.Get_SysElement(Data, repository);
                });
            }
        }


        public List<Requirement> Get_Requirements(Database Data, EA.Repository repository, List<string> m_Stereotype, Loading_OpArch Loading, List<string> m_Type)
        {
            Loading.Refresh();
            List<Requirement> m_Requirement = new List<Requirement>();

            Interface_Collection_Requirements interface_Collection = new Interface_Collection_Requirements();
            List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            if (m_Guid != null)
            {
                Loading.progressBar1.Maximum = m_Guid.Count;
                Loading.progressBar1.Refresh();

                int i1 = 0;
                do
                {
                    Requirement recent = new Requirement(m_Guid[i1], Data.metamodel);
                    recent.Get_Tagged_Values_From_Requirement(m_Guid[i1], repository, Data);
                    //   recent.Update_Requirement(repository, Data, recent.AFO_TITEL, recent.AFO_TEXT, recent.W_OBJEKT, recent.W_PROZESSWORT, recent.W_QUALITAET, recent.W_RANDBEDINGUNG, recent.W_SINGULAR, recent.W_SUBJEKT, recent.W_ZU, recent.W_NUTZENDER);
                    m_Requirement.Add(recent);

                    Loading.progressBar1.PerformStep();
                    Loading.Refresh();

                    i1++;
                } while (i1 < m_Guid.Count);
            }




            if (m_Requirement.Count > 0)
            {
                return (m_Requirement);
            }
            else
            {
                return (null);
            }
        }

        public List<Requirement> Get_Requirments_To_Export(Database Data, EA.Repository repository, Loading_OpArch Loading)
        {
            List<Requirement> m_ret = new List<Requirement>();

            Repsoitory_Elements.Repository_Elements repository_Elements = new Repsoitory_Elements.Repository_Elements();

            List<Requirement> m_req = repository_Elements.Get_Requirements_wo_TV(Data, repository, Data.metamodel.m_Requirement.Select(x => x.Stereotype).ToList(), Loading, Data.metamodel.m_Requirement.Select(x => x.Type).ToList());


            //TV RPI_Export && Bewertung erhalten
            
            if(m_req != null)
            {
                if(m_req.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        m_req[i1].Get_RPI_Export(Data);

                        if(m_req[i1].RPI_Export == true)
                        {
                            m_req[i1].Get_Operative_Bewertung(Data);

                            m_ret.Add(m_req[i1]);
                        }

                        i1++;
                    } while (i1 < m_req.Count);
                }
                
            }

            return (m_ret);
        }

        private List<Requirement> Get_Requirements_wo_TV(Database Data, EA.Repository repository, List<string> m_Stereotype, Loading_OpArch Loading, List<string> m_Type)
        {
            Loading.Refresh();
            List<Requirement> m_Requirement = new List<Requirement>();



            Interface_Collection_Requirements interface_Collection = new Interface_Collection_Requirements();
            List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            if (m_Guid != null)
            {
                Loading.progressBar1.Maximum = m_Guid.Count;
                Loading.progressBar1.Refresh();

                int i1 = 0;
                do
                {
                    Requirement recent = new Requirement(m_Guid[i1], Data.metamodel);
                   // recent.Get_Tagged_Values_From_Requirement(m_Guid[i1], repository, Data);
                    //   recent.Update_Requirement(repository, Data, recent.AFO_TITEL, recent.AFO_TEXT, recent.W_OBJEKT, recent.W_PROZESSWORT, recent.W_QUALITAET, recent.W_RANDBEDINGUNG, recent.W_SINGULAR, recent.W_SUBJEKT, recent.W_ZU, recent.W_NUTZENDER);
                    m_Requirement.Add(recent);

                    Loading.progressBar1.PerformStep();
                    Loading.Refresh();

                    i1++;
                } while (i1 < m_Guid.Count);
            }




            if (m_Requirement.Count > 0)
            {
                return (m_Requirement);
            }
            else
            {
                return (null);
            }
        }

        public void Get_Requirements_WithConnector_Parallel(Database database, EA.Repository repository, int type)
        {
            List<Requirement> m_Requirement = new List<Requirement>();

            //Interface_Collection interface_Collection = new Interface_Collection();
            //List<string> m_Guid = interface_Collection.Get_Elements_GUID(Data, m_Type, m_Stereotype);

            //Anforderungen erhalten
            List<string> m_Guid = Get_Requirements_GUID(database, database.metamodel.m_Requirement.Select(x => x.Type).ToList(), database.metamodel.m_Requirement.Select(x => x.Stereotype).ToList());

            if (m_Guid != null)
            {
                Parallel.ForEach(m_Guid, guid =>
                {
                    Requirement recent = new Requirement(guid, database.metamodel);
                    recent.ID = recent.Get_Object_ID(database);
                    recent.Get_RPI_Export(database);
                    recent.Get_Anforderungsart(database);
                    m_Requirement.Add(recent);
                });


                database.m_Requirement = m_Requirement;
                //Konnektoren erhalten
                //type == 0 Replaces

                if(type != -1)
                {
                    Parallel.ForEach(database.m_Requirement, requirement =>
                    {
                        if (type == 0)
                        {
                            requirement.Get_Connector_Replaces(database, repository);
                        }
                       

                    });

                    
                }

                Parallel.ForEach(database.m_Requirement, requirement =>
                {
                    if (type == -1)
                    {
                        requirement.Get_Connector_Refines(database, repository);
                    }


                });



            }

        }
       
        
        public List<string> Get_Requirements_Package(int  Package_id, EA.Repository repository, List<string> req_guid)
        {
            List<string> m_ret = new List<string>();

            EA.Element element;
            EA.Collection collection = repository.GetPackageByID(Package_id).Elements;

            if(collection.Count > 0)
            {
                short i1 = 0;
                do
                {
                    element = collection.GetAt(i1);

                    if (req_guid.Contains(element.ElementGUID) == true)
                    {
                        m_ret.Add(element.ElementGUID);
                    }

                    i1++;
                } while (i1 < collection.Count);
            }

            EA.Package Package;
            EA.Collection collection2 = repository.GetPackageByID(Package_id).Packages;

            if (collection2.Count > 0)
            {
                short i1 = 0;
                do
                {
                    Package = collection2.GetAt(i1);

                    List<string> m_help = Get_Requirements_Package(Package.PackageID, repository, req_guid);

                    if(m_help.Count > 0)
                    {
                        m_ret.AddRange(m_help);
                    }

                    i1++;
                } while (i1 < collection2.Count);
            }

            return (m_ret);
        }
        
        private List<string> Get_Elements_By_Type(List<string> m_Type, Database database, EA.Repository repository)
        {
           
            Interface_Collection interface_Collection = new Interface_Collection();
            List<string> m_Guid = interface_Collection.Get_Elements_By_Type_GUID(database, m_Type);

            return (m_Guid);
        }

       // private List<string> Get_Packages_Parallel(EA.Repository repository)
        #endregion Get_Elements

        #region Check Elements
        public List<string> Check_GUID_t_object(Database database, string GUID)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            List<string> m_GUID = new List<string>();
            m_GUID.Add(GUID);
            return (interface_Collection.Check_Element(database, m_GUID, null, null));
        }
        public List<string> Check_Element_t_object(Database database, List<string> m_Type, List<string> m_Stereotype, List<string> m_GUID)
        {
            Interface_Collection interface_Collection = new Interface_Collection();
            return (interface_Collection.Check_Element(database, m_GUID, m_Type, m_Stereotype));
        }
        #endregion Check_Elements

        #region Glossar Element
        public List<string> Get_Glossar_Element_IDS(Database database)
        {
            Interface_Glossar interface_Glossar = new Interface_Glossar();
            return (interface_Glossar.Get_Glosar_ID(database));

        }

        public string Get_Glossar_Property(Database database, string Property, string ID)
        {
            Interface_Glossar interface_Glossar = new Interface_Glossar();
            return (interface_Glossar.Get_Glossar_Property(Property, ID, database));
        }
        #endregion Glossar Element

        #region Activate Deactivate Export
        public void Change_Export_Status(EA.Collection m_col, bool flag_status, Database Data, EA.Repository repository)
        {
            Repository_Element repository_Element = new Repository_Element();
            EA.Element element;

            //Schleife über die Collection
            if (m_col.Count > 0)
            {
                short i1 = 0;
                do
                {
                    bool flag_update = false;
                    bool flag_req = false;
                    element = m_col.GetAt(i1);

                    //Element_Definition
                    if (Data.metamodel.m_Elements_Definition.Select(x => x.Type).ToList().Contains(element.Type) && Data.metamodel.m_Elements_Definition.Select(x => x.Stereotype).ToList().Contains(element.Stereotype))
                    {
                        flag_update = true;
                    }
                    //Element_Usage
                    if (Data.metamodel.m_Elements_Usage.Select(x => x.Type).ToList().Contains(element.Type) && Data.metamodel.m_Elements_Usage.Select(x => x.Stereotype).ToList().Contains(element.Stereotype))
                    {
                        flag_update = true;
                    }
                    //Requirement
                    if (Data.metamodel.m_Requirement.Select(x => x.Type).ToList().Contains(element.Type) && Data.metamodel.m_Requirement.Select(x => x.Stereotype).ToList().Contains(element.Stereotype))
                    {
                        flag_update = true;
                        flag_req = true;
                    }

                    if (flag_update == true)
                    {
                        //Update Repository
                        List<DB_Insert> m_Insert = new List<DB_Insert>();
                        m_Insert.Add(new DB_Insert(Data.metamodel.SYS_Inst_Tagged_Values[4].Name, OleDbType.VarChar, OdbcType.VarChar, flag_status.ToString(), -1));

                        repository_Element.Classifier_ID = element.ElementGUID;
                        repository_Element.ID = repository_Element.Get_Object_ID(Data);
                        repository_Element.Update_TV(m_Insert, Data, repository);

                        //NodeType in Database ändern{
                        if (flag_req == false)
                        {
                            List<NodeType> m_recent = Data.m_NodeType.Where(x => x.Instantiate_GUID == repository_Element.Classifier_ID).ToList();
                            if (m_recent.Count > 0)
                            {
                                m_recent.ForEach(x => x.RPI_Export = flag_status);
                            }
                        }
                        else
                        {
                            List<Requirement> m_req = Data.m_Requirement.Where(x => x.Classifier_ID == repository_Element.Classifier_ID).ToList();
                            if (m_req.Count > 0)
                            {
                                m_req.ForEach(x => x.RPI_Export = flag_status);
                            }
                        }
                    }

                    i1++;
                } while (i1 < m_col.Count);
            }

        }

        public void Change_Package_Export_Status(EA.Package package, bool flag_status, Database Data, EA.Repository repository)
        {

            EA.Package package_child;
            EA.Collection m_col = package.Elements;
          
            if(m_col.Count > 0)
            {
                this.Change_Export_Status(m_col, flag_status, Data, repository);
            }

            EA.Collection m_col_Packages = package.Packages;

            if(m_col_Packages.Count > 0)
            {
                short i1 = 0;
                do
                {
                    package_child = m_col_Packages.GetAt(i1);

                    this.Change_Package_Export_Status(package_child, flag_status, Data, repository );

                    i1++;
                } while (i1 < m_col_Packages.Count);
            }


        }
        #endregion  Activate Deactivate Export

        #region Archiv
        /* public List<string> Check_GUID_t_object(Database database, string GUID)
         {
             XML xml = new XML();

             if (GUID != null)
             {
                 List<DB_Input[]> ee = new List<DB_Input[]>();
                 DB_Input[] help = { new DB_Input(-1, GUID) };
                 ee.Add(help);
                 string[] m_output = { "ea_guid" };
                 string table = "t_object";
                 string[] m_input_Property = { "ea_guid" };
                 OleDbType[] m_input_Type = { OleDbType.VarChar };

                 List<DB_Return> m_ret = xml.Read_Attribut(m_output, table, m_input_Property, ee, m_input_Type, database);

                 if (m_ret[0].Ret.Count > 1)
                 {
                     return (m_ret[0].Ret.GetRange(1, m_ret[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
                 }
             }
             return (null);
         }
         /* public List<Requirement> Get_Requirements(Database Data, EA.Repository repository, List<string> m_Stereotype, Loading_OpArch Loading, List<string> m_Type)
          {
              Loading.Refresh();
              XML xML = new XML();
              DB_Command command = new DB_Command();
              List<Requirement> m_Requirement = new List<Requirement>();
              List<string> m_Guid = new List<string>();
              string SQL = "";
              List<DB_Input[]> ee = new List<DB_Input[]>();
              string[] m_output = { "Stereotype" };
              OleDbCommand SELECT1 = new OleDbCommand(SQL, Data.oLEDB_Interface.dbConnection);
              if (m_Stereotype.Count > 0)
              {
                  SQL = "SELECT ea_guid FROM t_object WHERE Stereotype IN(" + command.Add_Parameters_Pre(m_Stereotype.ToArray()) + ") AND Object_Type IN(" + command.Add_Parameters_Pre(m_Type.ToArray()) + ")";
                  ee.Add(m_Stereotype.Select(x => new DB_Input(-1, x)).ToArray());
                  ee.Add(m_Type.Select(x => new DB_Input(-1, x)).ToArray());
                  OleDbType[] m_input_Type = { OleDbType.VarChar, OleDbType.VarChar };
                  SELECT1.CommandText = SQL;
                  Data.oLEDB_Interface.Add_Parameters_Select(SELECT1, ee, m_input_Type);
              }
              else
              {
                  SQL = "SELECT ea_guid FROM t_object WHERE Object_Type IN(" + command.Add_Parameters_Pre(m_Type.ToArray()) + ")";
                  ee.Add(m_Type.Select(x => new DB_Input(-1, x)).ToArray());
                  OleDbType[] m_input_Type = { OleDbType.VarChar };
                  SELECT1.CommandText = SQL;
                  Data.oLEDB_Interface.Add_Parameters_Select(SELECT1, ee, m_input_Type);
              }


              List<DB_Return> m_ret3 = Data.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT1, m_output);

              if (m_ret3[0].Ret.Count > 1)
              {
                  m_Guid = m_ret3[0].Ret.GetRange(1, m_ret3[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList();
              }
              else
              {
                  m_Guid = null;
              }


              if (m_Guid != null)
              {
                  Loading.progressBar1.Maximum = m_Guid.Count;
                  Loading.progressBar1.Refresh();

                  int i1 = 0;
                  do
                  {
                      Requirement recent = new Requirement(m_Guid[i1]);
                      recent.Get_Tagged_Values_From_Requirement(m_Guid[i1], repository, Data);
                      //   recent.Update_Requirement(repository, Data, recent.AFO_TITEL, recent.AFO_TEXT, recent.W_OBJEKT, recent.W_PROZESSWORT, recent.W_QUALITAET, recent.W_RANDBEDINGUNG, recent.W_SINGULAR, recent.W_SUBJEKT, recent.W_ZU, recent.W_NUTZENDER);
                      m_Requirement.Add(recent);

                      Loading.progressBar1.PerformStep();
                      Loading.Refresh();

                      i1++;
                  } while (i1 < m_Guid.Count);
              }

              if (m_Requirement.Count > 0)
              {
                  return (m_Requirement);
              }
              else
              {
                  return (null);
              }

          }
          /// <summary>
          /// Es werden die GUID von allen Logical zurückgegeben
          /// </summary>
          /// <param name="Repository"></param>
          /// <returns></returns>
          /* public List<string> Get_Logicals_GUID2(EA.Repository Repository, Database database)
           {
               XML xML = new XML();
               List<string> m_GUID = new List<string>();

               List<string> m_Type = database.metamodel.m_Szenar.Select(x => x.Type).ToList();
               List<string> m_Stereotype = database.metamodel.m_Szenar.Select(x => x.Stereotype).ToList();

               List<DB_Input[]> ee = new List<DB_Input[]>();
               ee.Add(m_Type.Select(x => new DB_Input(-1, x)).ToArray());
               ee.Add(m_Stereotype.Select(x => new DB_Input(-1, x)).ToArray());
               string[] m_output = { "Object_ID" };
               string[] m_output2 = { "ea_guid" };
               string table = "t_object";
               string[] m_input_Property = { "Object_Type", "Stereotype" };
               OleDbType[] m_input_Type = { OleDbType.VarChar, OleDbType.VarChar };
               DB_Command command = new DB_Command();

               if (database.metamodel.flag_Analyse_Diagram == true)
               {
                   //Im Diagramm
                   OleDbCommand SELECT = command.Get_Select_Command(table, m_output, m_input_Property, ee, database.oLEDB_Interface.dbConnection);
                   database.oLEDB_Interface.Add_Parameters_Select(SELECT, ee, m_input_Type);
                   SELECT.CommandText = "SELECT ea_guid FROM t_object WHERE Object_ID IN (SELECT Object_ID FROM t_diagramobjects WHERE Object_ID IN (" + SELECT.CommandText + "))";
                   List<DB_Return> m_ret = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT, m_output2);

                   if (m_ret[0].Ret.Count > 1)
                   {
                       m_GUID = (m_ret[0].Ret.GetRange(1, m_ret[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
                   }
                   else
                   {
                       m_GUID = (null);
                   }
               }
               else
               {
                   OleDbCommand SELECT2 = command.Get_Select_Command(table, m_output2, m_input_Property, ee, database.oLEDB_Interface.dbConnection);
                   database.oLEDB_Interface.Add_Parameters_Select(SELECT2, ee, m_input_Type);
                   List<DB_Return> m_ret2 = database.oLEDB_Interface.oleDB_SELECT_One_Table(SELECT2, m_output2);

                   if (m_ret2[0].Ret.Count > 1)
                   {
                       m_GUID = (m_ret2[0].Ret.GetRange(1, m_ret2[0].Ret.Count - 1).ToList().Select(x => x.ToString()).ToList());
                   }
                   else
                   {
                       m_GUID = (null);
                   }
               }

               if(m_GUID != null)
               {
                   if(m_GUID.Count> 0)
                   {
                       return (m_GUID);
                   }


               }

               return (null);


           }
           */
        #endregion Archiv

        #region Update
        public void Update_NodeTypes_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_NodeTypes(database);

         

            if (m_guid != null)
            {
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update NodeType";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    NodeType recent = new NodeType(null, null, null);
                    recent.Classifier_ID = guid;
                    recent.Update_Repository_Class(database, repository);
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }

        }

        public void Update_SysElemente_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_SysElemente(database);

    
            if (m_guid != null)
            {
               
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update SysElemente";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    SysElement recent = new SysElement(null, null, null);
                    recent.Classifier_ID = guid;
                    recent.Update_Repository_Class(database, repository);
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }

        }

        public void Update_ReqCategory_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Capability_GUID(repository, database);

           

            if (m_guid != null)
            {
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update Capability";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    Capability recent = new Capability(null, null, null);
                    recent.Classifier_ID = guid;
                    recent.Update_Repository_Class(database, repository);
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }

        }

        public void Update_Logical_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Logicals_GUID2(database);

          

            if (m_guid != null)
            {
                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update Logical";
                load.progressBar1.Value = 0;
                load.Refresh();
                //NodeType Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    Logical recent = new Logical(null, null);
                    recent.Classifier_ID = guid;
                    recent.Update_Repository_Class(database, repository);
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }

        }

        public void Update_Nachweisarten_Parallel(Database database, EA.Repository repository, Loading_OpArch load)
        {
            List<string> m_guid = this.Get_Nachweisarten(database);

            if (m_guid != null)
            {

                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update Nachweisarten";
                load.progressBar1.Value = 0;
                load.Refresh();
                //Nachweisart Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    Nachweisart recent = new Nachweisart(null, null, null);
                    recent.Classifier_ID = guid;
                    recent.ID = recent.Get_Object_ID(database);
                    recent.Get_TV_Nachweisart(database, repository);
                    recent.Notes = recent.Get_Notes(database);
                    recent.abnahmekriterium = recent.Notes;
                    
                    recent.Update_Abnahmekriterium(repository, database);
                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }
        }

        public void Update_Anforderungen_Nachweisarten_Parallel(Database Data, EA.Repository repository, Loading_OpArch load)
        {
            #region Stereotype
            //Erhalten Stereotypen
            List<string> m_Type1 = Data.metamodel.m_Requirement_Functional.Select(x => x.Type).ToList();
            List<string> m_Type2 = Data.metamodel.m_Requirement_Interface.Select(x => x.Type).ToList();
            List<string> m_Type3 = Data.metamodel.m_Requirement_User.Select(x => x.Type).ToList();
            List<string> m_Type4 = Data.metamodel.m_Requirement_Design.Select(x => x.Type).ToList();
            List<string> m_Type5 = Data.metamodel.m_Requirement_Process.Select(x => x.Type).ToList();
            List<string> m_Type6 = Data.metamodel.m_Requirement_Environment.Select(x => x.Type).ToList();
            List<string> m_Type7 = Data.metamodel.m_Requirement_Typvertreter.Select(x => x.Type).ToList();
            List<string> m_Type8 = Data.metamodel.m_Requirement_Quality_Class.Select(x => x.Type).ToList();
            List<string> m_Type81 = Data.metamodel.m_Requirement_Quality_Activity.Select(x => x.Type).ToList();
            List<string> m_Type9 = Data.metamodel.m_Requirement_NonFunctional.Select(x => x.Type).ToList();

            if (m_Type2.Count > 0)
            {
                m_Type1.AddRange(m_Type2);
            }
            if (m_Type3.Count > 0)
            {
                m_Type1.AddRange(m_Type3);
            }
            if (m_Type4.Count > 0)
            {
                m_Type1.AddRange(m_Type4);
            }
            if (m_Type5.Count > 0)
            {
                m_Type1.AddRange(m_Type5);
            }
            if (m_Type6.Count > 0)
            {
                m_Type1.AddRange(m_Type6);
            }
            if (m_Type7.Count > 0)
            {
                m_Type1.AddRange(m_Type7);
            }
            if (m_Type8.Count > 0)
            {
                m_Type1.AddRange(m_Type8);
            }
            if (m_Type81.Count > 0)
            {
                m_Type1.AddRange(m_Type81);
            }
            if (m_Type9.Count > 0)
            {
                m_Type1.AddRange(m_Type9);
            }


            // List<string> m_Stereotype = repository_Elements.Get_Stereotpye_Requirements(m_Type1, Data);
            //Stereotypen der AFo erhalten
            #region Add Stereptype Requirement

            List<string> m_Stereotype = new List<string>();
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Functional.Select(x => x.Stereotype).ToList());
           
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Design.Select(x => x.Stereotype).ToList());
           
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Interface.Select(x => x.Stereotype).ToList());
           
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Process.Select(x => x.Stereotype).ToList());
           
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Typvertreter.Select(x => x.Stereotype).ToList());
           
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_Environment.Select(x => x.Stereotype).ToList());
            
                m_Stereotype.AddRange(Data.metamodel.m_Requirement_User.Select(x => x.Stereotype).ToList());

            m_Stereotype.AddRange(Data.metamodel.m_Requirement_Quality_Class.Select(x => x.Stereotype).ToList());
            m_Stereotype.AddRange(Data.metamodel.m_Requirement_Quality_Activity.Select(x => x.Stereotype).ToList());

            m_Stereotype.AddRange(Data.metamodel.m_Requirement_NonFunctional.Select(x => x.Stereotype).ToList());


            m_Stereotype.Add("none");
            #endregion
            #endregion
            List<string> m_guid = this.Get_Requirements_GUID(Data, m_Type1, m_Stereotype);

            if (m_guid != null)
            {

                load.progressBar1.Maximum = 2;
                load.label_Progress.Text = "Update Anforderungen Nachweisarten";
                load.progressBar1.Value = 0;
                load.Refresh();
                //Nachweisart Updaten
                Parallel.ForEach(m_guid, guid =>
                {
                    Requirement req = new Requirement(null, Data.metamodel);
                    req.Classifier_ID = guid;
                    req.ID = req.Get_Object_ID(Data);
                    req.Get_Nachweisarten(Data, repository, false);
                    req.Update_TV_Nachweisart(Data,repository);


                });
                load.progressBar1.PerformStep();
                load.progressBar1.Update();

            }
        }

        public void Update_Anforderungen_MDG(Database Data, EA.Repository repository, string Type, string Stereotype, string mdg)
        {

            List<string> m_Type = new List<string>();
            m_Type.Add(Type);
            List<string> m_Stereotype = new List<string>();
            m_Stereotype.Add(Stereotype);

            List<string> m_guid = this.Get_Requirements_GUID2(Data, m_Type, m_Stereotype);

            Requirement_Plugin.Interfaces.Interface_TaggedValue interface_TaggedValue = new Interface_TaggedValue();

            if(m_guid != null)
            {
                if (m_guid.Count > 0)
                {
                    int i1 = 0;
                    do
                    {
                        interface_TaggedValue.Set_Stereotype(m_guid[i1], mdg, Stereotype, Data);

                        i1++;
                    } while (i1 < m_guid.Count);
                }

            }


        }
        #endregion

        # region Issue
        public void Create_Issue_Nachweisart_Mehrfach(List<string> m_guid, Database database, EA.Repository repository, List<string> m_Package_GUID)
        {
            if(m_guid != null)
            {
                if(m_guid[0] != null)
                {
                    EA.Element req = repository.GetElementByGuid(m_guid[0]);
                    Repository_Connector repository_Connector = new Repository_Connector();
                    //Issue erzeugen
                    string name = "Anforderungen <<" + req.Name + ">> ist mit mehreren Nachweisarten verknüpft";
                    string notes = "Eine Anforderung darf nur eine Nachweisart aufweisen. Es müssen die Nachweisarten auf eine Nachweisart reduziert werden.";
                    string type = database.metamodel.m_Issue[8].Stereotype;
                    Issue issue = new Issue(database, name, notes, m_Package_GUID[0], repository, true, type);

                    int i1 = 0;
                    do
                    {
                        if (issue.Classifier_ID != null && m_guid[i1] != null)
                        {
                            repository_Connector.Create_Dependency(issue.Classifier_ID, m_guid[i1], database.metamodel.m_Con_Trace.Select(x => x.Stereotype).ToList(), database.metamodel.m_Con_Trace.Select(x => x.Type).ToList(), database.metamodel.m_Con_Trace.Select(x => x.SubType).ToList()[0], repository, database, database.metamodel.m_Con_Trace.Select(x => x.Toolbox).ToList()[0], database.metamodel.m_Con_Trace[0].direction);
                        }

                        i1++;
                    } while (i1 < m_guid.Count);
                }
               
            }
        }

        public void Create_Issue_Nachweisart_Abgleich(List<string> m_guid, Database database, EA.Repository repository, List<string> m_Package_GUID)
        {
            if (m_guid != null)
            {
                if(m_guid[0] != null)
                {
                    EA.Element req = repository.GetElementByGuid(m_guid[0]);
                    Repository_Connector repository_Connector = new Repository_Connector();
                    //Issue erzeugen
                    string name = "Anforderungen <<" + req.Name + ">> stimmt nicht mit der Nachweisart überein";
                    string notes = "Die TaggedValue der Anforderung (Abnahemkriterium, Nachweisart) müssen mit der verknüpften Nachweisart übereinstimmen.";
                    string type = database.metamodel.m_Issue[8].Stereotype;
                    Issue issue = new Issue(database, name, notes, m_Package_GUID[0], repository, true, type);

                    int i1 = 0;
                    do
                    {
                        if (issue.Classifier_ID != null && m_guid[i1] != null)
                        {
                            repository_Connector.Create_Dependency(issue.Classifier_ID, m_guid[i1], database.metamodel.m_Con_Trace.Select(x => x.Stereotype).ToList(), database.metamodel.m_Con_Trace.Select(x => x.Type).ToList(), database.metamodel.m_Con_Trace.Select(x => x.SubType).ToList()[0], repository, database, database.metamodel.m_Con_Trace.Select(x => x.Toolbox).ToList()[0], database.metamodel.m_Con_Trace[0].direction);
                        }

                        i1++;
                    } while (i1 < m_guid.Count);
                }
                
            }
        }

        public List<Issue> Get_Issues_Connetoren(List<string> m_guid, Database database, EA.Repository repository)
        {
            List<Issue> m_Issue_Con = new List<Issue>();
            List<string> m_help = new List<string>();
            m_help.Add("Issue");
            List<string> m_issue_guid = this.Get_Elements_By_Type(m_help, database, repository);

            List<Issue> m_Issue = new List<Issue>();

            if(m_issue_guid.Count > 0)
            {
                int i1 = 0;
                do
                {
                    Issue issue = new Issue(database, "", "", "", repository, false, null );
                    issue.Classifier_ID = m_issue_guid[i1];
                    issue.Get_TV_Connector(database);
                    m_Issue.Add(issue);

                    i1++;
                } while (i1 < m_issue_guid.Count);

                
                m_Issue_Con = m_Issue.Where(x => m_guid.Contains(x.Con_guid) == true).ToList();

                
            }

            return (m_Issue_Con);
        }
        #endregion

        #region Misc
        public string Correct_SQL_Strings(string String)
        {
            /* if(String != null)
             {
                 string ret = String;

                 //Gänsefüßen " statt '
                 ret = ret.Replace('\'', '"');

                 return ret;
             }
             else
             {
                 return null;
             }
             */

            return (String);

        }
        #endregion Misc

      

    }//end Repository_Elements

}//end namespace Requirement_Plugin