///////////////////////////////////////////////////////////
//  AFO_PROJEKTROLLE.cs
//  Implementation of the Enumeration AFO_PROJEKTROLLE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:42
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_PROJEKTROLLE : int {

		AG,
		AN,
        NULL
            //{"AG", "AN"}
	}//end AFO_PROJEKTROLLE

}//end namespace Anforderung