///////////////////////////////////////////////////////////
//  AFO_VERERBUNG.cs
//  Implementation of the Enumeration AFO_VERERBUNG
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:44
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_VERERBUNG : int {

		Ja,
		Nein,
        NULL
            // {"Ja", "Nein"};
	}//end AFO_VERERBUNG

}//end namespace Anforderung