///////////////////////////////////////////////////////////
//  AFO_QS_STATUS.cs
//  Implementation of the Enumeration AFO_QS_STATUS
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:42
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_QS_STATUS : int {

		ungeprueft,
		akzeptiert,
		bemaengelt,
            NULL
        //{"ungeprueft", "akzeptiert", "bemaengelt"};
    }//end AFO_QS_STATUS

}//end namespace Anforderung