///////////////////////////////////////////////////////////
//  AFO_BEZUG.cs
//  Implementation of the Enumeration AFO_BEZUG
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:36
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml;
using System.Linq;


namespace Ennumerationen
{
	public enum AFO_BEZUG : int {

		System,
		Unterstuetzungssystem,
		Angebot,
		Konzept,
		Lieferumfang,
		Projektdurchfuehrung,
		Vertrag,
		Organisation,
		Beistellung,
        NULL

        //var AFO_BEZUG = ["System", "Unterstuetzungssystem", "Angebot", "Konzept", "Lieferumfang", "Projektdurchfuehrung", "Vertrag", "Organisation", "Beistellung" ];
    }//end AFO_BEZUG

}//end namespace Anforderung