///////////////////////////////////////////////////////////
//  AFO_WV_ART.cs
//  Implementation of the Enumeration AFO_WV_ART
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:45
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	/// <summary>
	/// Reiter Anforderungsart in Require 7
	/// </summary>
	public enum AFO_WV_ART : int {

		Anforderung,
		Nutzerforderung,
		Systemanforderung,
		Prozessanforderung,
		Anwendungsfall,
		Randbedingung,
		Annahme,
		Regel,
		Fähigkeit,
		Geschäftsprozess,
		Feature,
		Parameter,
		Ziel,
		Bedrohung,
		Überschrift_Einleitung,
        NULL

        // {"Anforderung", "Nutzerforderung", "Systemanforderung", "Prozessanforderung",  "Anwendungsfall", "Randbedingung", "Annahme", "Regel","Fähigkeit", "Geschäftsprozess", "Feature","Parameter","Ziel","Bedrohung", "Überschrift/Einleitung"};

    }//end AFO_WV_ART

}//end namespace Anforderung