///////////////////////////////////////////////////////////
//  AFO_FUNKTIONAL.cs
//  Implementation of the Enumeration AFO_FUNKTIONAL
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:39
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_FUNKTIONAL : int {

		funktional,
		nicht_funktional,
        NULL
        // {funktional, nicht_funktional}
    }//end AFO_FUNKTIONAL

}//end namespace Anforderung