///////////////////////////////////////////////////////////
//  AFO_OPERATIVEBEWERTUNG.cs
//  Implementation of the Enumeration AFO_OPERATIVEBEWERTUNG
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:40
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_OPERATIVEBEWERTUNG : int {

		kritisch,
		essentiell,
		notwendig,
		unerheblich,
        NULL
        //{"kritisch", "essentiell", "notwendig", "unerheblich"}
    }//end AFO_OPERATIVEBEWERTUNG

}//end namespace Anforderung