///////////////////////////////////////////////////////////
//  AFO_KRITIKALITAET.cs
//  Implementation of the Enumeration AFO_KRITIKALITAET
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:40
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
    public enum AFO_KRITIKALITAET : int {

        A1,
        A2,
        A3,
        B1,
        B2,
        B3,
        C1,
        C2,
        C3,
        unbestimmt,
         NULL
           // {A1,A2,A3,B1, B2, B3,C1,C2,C3, unbestimmt}
    
	}//end AFO_KRITIKALITAET

}//end namespace Anforderung