///////////////////////////////////////////////////////////
//  AFO_PRIORITAET_VERGABE.cs
//  Implementation of the Enumeration AFO_PRIORITAET_VERGABE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:41
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_PRIORITAET_VERGABE : int {

		kritisch,
		essentiell,
		notwendig,
		unerheblich,
        NULL
        //{"kritisch", "essentiell", "notwendig", "unerheblich"};
    }//end AFO_PRIORITAET_VERGABE

}//end namespace Anforderung