///////////////////////////////////////////////////////////
//  AFO_WV_PHASE.cs
//  Implementation of the Enumeration AFO_WV_PHASE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:46
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_WV_PHASE : int {

		Konzept,
		Prototyp,
		Einsatzreife,
		RollOut,
		phasenübergreifend,
        NULL

        //{"Konzept", "Prototyp", "Einsatzreife", "Roll-Out", "phasenübergreifend"}
    }//end AFO_WV_PHASE

}//end namespace Anforderung