///////////////////////////////////////////////////////////
//  AFO_CPM_PHASE.cs
//  Implementation of the Enumeration AFO_CPM_PHASE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:37
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum AFO_CPM_PHASE : int {
        
		Null,
		Eins,
		Zwei,
		Drei,
		Vier,
		Default,
        NULL
            // var AFO_CPM_PHASE = [0,1,2,3,4,99];

	}//end AFO_CPM_PHASE

}//end namespace Anforderung