///////////////////////////////////////////////////////////
//  AFO_WV_NACHWEISART.cs
//  Implementation of the Enumeration AFO_WV_NACHWEISART
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:45
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
    public enum AFO_WV_NACHWEISART : int {

        unbestimmt,
        Prüffall,
        Review,
        TestReleaseUnit,
        TestReleasePackage,
        Systemnachweis,
        Konformitätsnachweis,
        Übergabenachweis,
        Selbsterklärung,
        Annahmeprüfung,
        Sichtprüfung,
        Installationstest,
        ServiceKonformitätsprüfung,
        TestFunktionalerAnforderungen,
        TestnichtfunktionalerQualitätskriterienSLATeil1,
        Kompatibilitätstest,
        Koexistenztest,
        InteroperabilitätstestVerifikation,
        TestnichtfunktionalerQualitätskriterienSLATeil2,
        ZulassungITSicherheit,
        TestITSicherheitsanforderungen,
        PrüfungMigrationsverfahren,
        TestSWFunktionalitätderMigration,
        TestDatenmigration,
        TestRollenundRechtemigration,
        TestDatenqualitätTeil1,
        TestDatenqualitätTeil2,
        TestNutzeranforderungenUserFunctionality,
        InteroperabilitätstestValidierung,
        SzenarbasierterTest,
        Einsatzprüfung,
        TestQualityinUse,
        Betreibbarkeitsprüfungnichttechnisch,
        DeploymentQualityTest,
        Betreibbarkeitstest,
        QualityinOperationsMonitoringDauertest,
        Sonstiges,
        keinNachweis,
        NULL


            // { "unbestimmt",
            /*
        "Prüffall",
        "Review",
        "Test Release Unit",
        "Test Release Package",
        "Systemnachweis",
        "Konformitätsnachweis",
        "Übergabenachweis",
        "Selbsterklärung",
        "Annahmeprüfung",
        "Sichtprüfung",
        "Installationstest",
        "Service-Konformitätsprüfung",
        "Test Funktionaler Anforderungen",
        "Test nicht-funktionaler Qualitätskriterien (SLA Teil1)",
        "Kompatibilitätstest",
        "Koexistenztest",
        "Interoperabilitätstest (Verifikation)",
        "Test nicht-funktionaler Qualitätskriterien (SLA Teil2)",
        "Zulassung IT-Sicherheit","Test IT-Sicherheitsanforderungen","Prüfung Migrationsverfahren","Test SW-Funktionalität der Migration", "Test Datenmigration","Test Rollen- und Rechtemigration","Test Datenqualität Teil 1", "Test Datenqualität Teil 2", "Test Nutzeranforderungen (User Functionality)", "Interoperabilitätstest (Validierung)","Szenarbasierter Test","Einsatzprüfung","Test Quality in Use","Betreibbarkeitsprüfung (nicht-technisch)","Deployment Quality Test","Betreibbarkeitstest","Quality in Operations Monitoring / Dauertest","Sonstiges","kein Nachweis"};
    */
    }//end AFO_WV_NACHWEISART

}//end namespace Anforderung