///////////////////////////////////////////////////////////
//  AFO_DETAILSTUFE.cs
//  Implementation of the Enumeration AFO_DETAILSTUFE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:38
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
    public enum AFO_DETAILSTUFE : int {

		Null,
		Eins,
		Zwei,
		Drei,
		Vier,
        NULL
    
        //{0,1,2,3,4}
	}//end AFO_DETAILSTUFE

}//end namespace Anforderung