///////////////////////////////////////////////////////////
//  IN_CATEGORY.cs
//  Implementation of the Enumeration IN_CATEGORY
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:47
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum IN_CATEGORY : int {

		Null,
		Dreiundvierzig,
        NULL

        //{0 ,43}
	}//end IN_CATEGORY

}//end namespace Anforderung