///////////////////////////////////////////////////////////
//  W_AKTIVITAET.cs
//  Implementation of the Enumeration W_AKTIVITAET
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 15:35:47
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	/// <summary>
	/// Bestimmt welcher AFO-Typ
	/// </summary>
	public enum W_AKTIVITAET : int
    {

		Minus,
		dieMöglichkeitbieten,
		fähigsein,
        NULL
        // {"-", "die Möglichkeit bieten", "fähig sein"}
    }//end W_AKTIVITAET

}//end namespace Anforderung