///////////////////////////////////////////////////////////
//  ST_AKTEUR_TYP.cs
//  Implementation of the Enumeration ST_AKTEUR_TYP
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 17:17:12
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum ST_AKTEUR_TYP : int {

		Human,
		Bewerter,
		Stakeholder,
        NULL
        //{"Human", "Bewerter", "Stakeholder"};
    }//end ST_AKTEUR_TYP

}//end namespace Stakeholder