///////////////////////////////////////////////////////////
//  ST_EINFLUSS.cs
//  Implementation of the Enumeration ST_EINFLUSS
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 17:17:13
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum ST_EINFLUSS : int {

		Null,
		Eins,
		Zwei,
		Drei,
        NULL
            //{"0", "1", "2", "3"};
	}//end ST_EINFLUSS

}//end namespace Stakeholder