///////////////////////////////////////////////////////////
//  ST_GRUPPE.cs
//  Implementation of the Enumeration ST_GRUPPE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 17:17:13
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum ST_GRUPPE : int {

		Kernteam,
		Operationell_Beteiligte,
		Geschaeftsfeld,
		Erweitertes_Umfeld,
		Sonstige,
        NULL
        //{"Kernteam", "Operationell_Beteiligte", "Geschaeftsfeld", "Erweitertes_Umfeld", "Sonstige"};
    }//end ST_GRUPPE

}//end namespace Stakeholder