///////////////////////////////////////////////////////////
//  ST_INTERESSE.cs
//  Implementation of the Enumeration ST_INTERESSE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 17:17:14
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum ST_INTERESSE : int {

		MinusDrei,
		MinusZwei,
		MinusEins,
		Null,
		Eins,
		Zwei,
		Drei,
        NULL
        // {"-3", "-2", "-1", "0", "1", "2", "3"};
	}//end ST_INTERESSE

}//end namespace Stakeholder