///////////////////////////////////////////////////////////
//  ST_WV_PHASE.cs
//  Implementation of the Enumeration ST_WV_PHASE
//  Generated by Enterprise Architect
//  Created on:      01-Aug-2018 17:17:15
//  Original author: OLtzS Yannick Otto
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Ennumerationen
{
	public enum ST_WV_PHASE : int {

		Analysephase,
		Realisierungsphase,
		Nutzungsphase,
		phasenübergreifend,
        NULL
        //{"Analysephase", "Realisierungsphase", "Nutzungsphase", "phasenübergreifend"};
    }//end ST_WV_PHASE

}//end namespace Stakeholder